package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "type_item",
#     deps = [
#     ],
# )

# hcp(
#     name = "type_section",
#     deps = [
#         "type_item",
#     ],
# )
