package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object("forward_decls")

# hcp(
#     name = "inlined_structures",
#     deps = [
#         "forward_decls",
#         "structure",
#     ],
# )

# hcp(
#     name = "structure",
#     deps = [
#         "@boost//:container",
#         "@boost//:variant",
#     ],
# )
