load("//bazel/cookbook/cpp:main.bzl", "cpp_main")

package(
    default_visibility = ["//visibility:public"],
)

# cpp_main(
#     name = "main",
#     deps = [
#         "@HashLib4CPP//:HashLib4CPP",
#     ],
# )
