#!/usr/bin/env bash
#WHAT IT DOES:
#puts lorem ipsum into your clipboard

#run as followed:
# lorem <number of paragraphs>
#running just 'lorem' will give you one paragraph
$output;
paragraph_count="$1";

array=( "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris eu sollicitudin dui. Curabitur augue augue, tincidunt sit amet laoreet at, dapibus et sem. Vivamus id iaculis dolor. Proin aliquam bibendum quam a laoreet. Duis tempus, ante at egestas imperdiet, nisi justo congue nisl, et malesuada elit nisl nec libero. Integer sodales mauris euismod dolor ullamcorper, et sagittis orci vestibulum. Aenean sed rhoncus tellus, ac venenatis augue. Aliquam nec dui vel eros pellentesque ultrices eget vestibulum turpis. Phasellus congue nec nibh a aliquet."
       "Aliquam ac mi diam. Nunc non elementum leo. Donec facilisis imperdiet lorem in luctus. Cras nec luctus libero. In commodo mi nec volutpat molestie. Nunc massa magna, vestibulum ut eleifend eu, consequat eleifend mi. Fusce dolor tellus, ornare in turpis vitae, maximus bibendum orci. Cras blandit mauris vel est rhoncus rhoncus. Ut sodales placerat magna, vitae egestas turpis luctus a. Morbi ornare finibus sem sed commodo. Maecenas iaculis venenatis fringilla. Suspendisse risus nulla, aliquam eu libero nec, venenatis commodo metus. Nam commodo massa dui, malesuada rhoncus eros suscipit eu. Maecenas posuere et nisl ut gravida."
       "Praesent pulvinar lacinia faucibus. Etiam ullamcorper augue at gravida pellentesque. Fusce non efficitur ipsum, quis maximus lacus. Duis hendrerit odio cursus mauris gravida, nec accumsan ipsum molestie. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas porttitor ipsum tortor, sed tristique mi tincidunt quis. Aenean dapibus placerat venenatis. Suspendisse facilisis pretium nisi, ac imperdiet sapien volutpat ut."
       "Suspendisse suscipit id justo at facilisis. Curabitur varius aliquet neque non dignissim. Donec pretium, tortor id iaculis vulputate, mi felis hendrerit turpis, quis tincidunt odio ex placerat nisi. Mauris molestie condimentum semper. Phasellus a elementum lorem. Phasellus justo orci, posuere ac nisi sit amet, fermentum pellentesque leo. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla non sagittis erat, sed tincidunt nunc. Sed scelerisque lacinia felis, in feugiat enim iaculis nec."
       "Etiam pretium placerat enim non feugiat. Phasellus in risus posuere eros gravida ornare sed at lectus. Ut vitae laoreet ligula, ut dignissim massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur ultricies ex nec congue rutrum. Aenean in leo massa. Sed in mi dignissim, malesuada quam vel, pulvinar enim. Integer ut pellentesque risus."
       "Nam tempus justo augue, non porta leo semper eget. Praesent quis mi id dui facilisis sodales. Morbi et consectetur leo. Maecenas ac aliquam tellus. Nunc velit lectus, iaculis at aliquam ac, efficitur ullamcorper lorem. Aliquam erat volutpat. Nullam lacus elit, vehicula ut tortor sed, rutrum elementum purus. Aliquam feugiat at dui sit amet ornare. Phasellus in lobortis risus, in fringilla tortor. Donec commodo congue elit, et bibendum lectus tincidunt non. Sed et velit molestie ligula imperdiet bibendum a vitae mi."
       )
shuffle

#if no paragraph count was given, set it to 1
if [ -z "$paragraph_count" ]; then
  paragraph_count="1";
fi

#build up paragraphs of lorem ipsum
#starts over at the beginning of the array when moving past the last element
offset=0
for (( c=0; c<$paragraph_count; ++c ))
do
  
  if [ $c -ne 0 ]; then
    output+="\n\n";
  fi;
  
  offset=$(($c/${#array[@]}));
  output+="${array[$c-(${#array[@]}*$offset)]}"
done

echo -e $output | pbcopy;
green_message "in clipboard ✓";
