#!/usr/bin/env bash
#sometimes I just want to paste my git log
#onto my billing timesheet, It gives me all the commit messages for the current day on the branch I'm on.
#TODO: change this so that it will look at all the branches and print anything I did for the current day.
#also, I never actually fill out my time sheet till the last minute, so just a dump of sections mon - fri would be good
git log --since="6am" --no-decorate --author="Trevor Hickey" --date=raw --reverse --pretty=format:%B | awk 'NF > 0' | sed '/^Merge/ d' | tr '\n' ';'

