package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "attribute_style_to_string_converter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/method/attributes/specific/parts:attribute_style",
#     ],
# )
