package(
    default_visibility = ["//visibility:public"],
)

cc_library(
     name = "lib",
     srcs = ["lib.cpp"],
     hdrs = ["lib.hpp"],
     deps = [
     ],
     linkopts = ["-lX11", "-lXext", "-lXpm"],
 )