package(default_visibility = ["//visibility:public"])

load("//bazel/rules/cpp:main.bzl", "cpp_main")
load("//bazel/rules/unilang:unilang_to_code.bzl", "unilang_to_code")

# Essays
unilang_to_code("linguistics")

unilang_to_code("language_context")

unilang_to_code("a_box_full_of_pencils")

# Unilang Documentation
unilang_to_code("unilang")
