package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "meta_manipulation_settings", deps = [
"//code/transcompilers/unilang/options/manipulation:comment_adjustment_settings"
])