package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lib",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = [
"//code/utilities/time/calendar/tm_wrappers:lib",
"//code/utilities/time/calendar/months:lib"
]
)