package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="flag_util", deps = [
    "//code/utilities/flags/data:flags",
    "//code/utilities/types/vectors/observers:lib",
])