#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#input parameters
image="$1"
x_cord="$2"
y_cord="$3"

#run alias
convert $image -crop '1x1+'"$x_cord"'+'"$y_cord" txt:- | last-line | cut -d' ' -f4