package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lib",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = ["//code/utilities/types/converters:lib",
"//code/utilities/types/strings/observers/converting:lib",
"//code/utilities/language_basic/control_structures/looping:lib",
"//code/utilities/language_basic/std_hackery:lib",

]
)
