package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "enum_argument_printer",
#     deps = [
#         "//code/utilities/comments/code:comment_creator",
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/other:lib",
#     ],
# )

# hcp(
#     name = "enum_boilerplate_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/other:lib",
#     ],
# )

# hcp(
#     name = "enum_value_creator",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/other:lib",
#     ],
# )

# hcp(
#     name = "enum_without_utility_values_printer",
#     deps = [
#         "enum_argument_printer",
#         "enum_boilerplate_printer",
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/other:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "enum_with_utility_values_printer",
#     deps = [
#         "enum_argument_printer",
#         "enum_boilerplate_printer",
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/other:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )
