package(
    default_visibility = ["//visibility:public"],
)

load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

cc_library(
    name = "matrix4x4f",
    hdrs = ["matrix4x4f.h"],
    deps = [
        "//code/utilities/data_structures/vector:vector3f",
    ],
)
