package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/cpp:main.bzl", "cpp_main")
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")

hcp(name = "thread_pool_getter", deps = ["@boost//:asio"])