load("//bazel/cookbook/cpp:main.bzl", "cpp_main")
package(
    default_visibility = ["//visibility:public"],
)

#cc_binary(
#    name = "main",
#    srcs = ["main.cpp"],
#    #copts = ["-L/usr/lib/x86_64-linux-gnu"],
#    linkopts = ["-lxcb"],
#    deps = [],
#)
