#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

ls -al --time-style=iso | squeeze-spaces | cut -d' ' -f6- | remove-first-3-lines | sort