package(default_visibility = ["//visibility:public"])

load("//bazel/rules/system:create_10M_file.bzl", "create_10M_file")
load("//bazel/rules/system:create_500M_file.bzl", "create_500M_file")
load("//bazel/rules/system:create_hello_world_file.bzl", "create_hello_world_file")

create_10M_file("test1")

create_500M_file("test2")

create_500M_file("test3")

create_500M_file("test4")

create_500M_file("test5")

create_500M_file("test6")

create_500M_file("test7")

create_hello_world_file("hello_world")
