package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="list_of_links",deps = [
    "//code/utilities/types/strings/transformers/appending:lib",
    "//code/utilities/formats/html:basic_html_template_getter",
    "//code/utilities/formats/html/body:html_list_maker",
    "//code/utilities/formats/html/style:link_list_styling",
])