package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

cpp_object(name = "printf_statement_kind")

# hcp(
#     name = "printf_code_generator",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#     ],
# )
