#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#this will wipe all the local changes
cd `git rev-parse --show-toplevel`;
git reset --hard HEAD && git clean -d -f;
cd -;

#sometimes I still have left over junk preventing me from checking out another branch
#git's interface is pretty much broken, so we then apply these changes as well:  
git rm -r --cached .
git reset --hard HEAD

#if the files still don't change, assume git is broken garbage.  
#ignore the files in question instead.  They probably aren't files you care about anyways
echo 'if files still exist try: update-index --assume-unchanged "file"'

#then re-run everything again.  At this point, I've never had it NOT work.
#you'll also want to make sure that your git configurations are set correctly.
#line endings and such.
