package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "enum_to_str_getter", deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/enum/item:enum_item",
"//code/tools/transcompilers/unilang/options/sections/enum:enum_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_enum/categories:enum_utility_conversion_function_options",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/tools/transcompilers/unilang/enum_printer/core:enum_value_creator",
"//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
"//code/utilities/types/strings/transformers/inflection:inflection_converter",
"//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
"//code/tools/transcompilers/unilang/structure/adjust/methods/creating_methods/via_enum:enum_utility_function_shared",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/transformers/casing:lib",
"//code/utilities/types/general:lib",
])

hcp(name = "enum_to_str_inflection_count_getter", deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/enum/item:enum_item",
"//code/tools/transcompilers/unilang/options/sections/enum:enum_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_enum/categories:enum_utility_conversion_function_options",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/tools/transcompilers/unilang/enum_printer/core:enum_value_creator",
"//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
"//code/utilities/types/strings/transformers/inflection:inflection_converter",
"//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
"//code/tools/transcompilers/unilang/structure/adjust/methods/creating_methods/via_enum:enum_utility_function_shared",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/transformers/casing:lib",
"//code/utilities/types/general:lib",
])

hcp(name = "enum_to_str_plural_getter", deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/enum/item:enum_item",
"//code/tools/transcompilers/unilang/options/sections/enum:enum_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_enum/categories:enum_utility_conversion_function_options",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/tools/transcompilers/unilang/enum_printer/core:enum_value_creator",
"//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
"//code/utilities/types/strings/transformers/inflection:inflection_converter",
"//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
"//code/tools/transcompilers/unilang/structure/adjust/methods/creating_methods/via_enum:enum_utility_function_shared",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/transformers/casing:lib",
"//code/utilities/types/general:lib",
])

hcp(name = "enum_to_str_singular_getter", deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/enum/item:enum_item",
"//code/tools/transcompilers/unilang/options/sections/enum:enum_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_enum/categories:enum_utility_conversion_function_options",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/tools/transcompilers/unilang/enum_printer/core:enum_value_creator",
"//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
"//code/utilities/types/strings/transformers/inflection:inflection_converter",
"//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
"//code/tools/transcompilers/unilang/structure/adjust/methods/creating_methods/via_enum:enum_utility_function_shared",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/transformers/casing:lib",
"//code/utilities/types/general:lib",
])