package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")


hcp(name = "bdf_settings", deps = [
	":xlfd_parts",
	":bdf_size",
	":character_segment",
])

hcp(name = "xlfd_parts", deps = [
])

hcp(name = "bdf_size", deps = [
])

hcp(name = "character_segment", deps = [
])
