package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "comment_adjuster",
#     deps = [
#         "//code/utilities/types/strings/observers/splitting:words_deriver",
#         "//code/utilities/linguistics/grammar:grammar_adjuster",
#         "//code/utilities/linguistics/grammar/settings:comment_grammar_settings",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "words_deriver",
#     deps = [
#         "//code/utilities/types/strings/observers/char:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "module_dependency_resolver",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings:file_type",
#     ],
# )

# hcp(
#     name = "structure_adjuster",
#     deps = [
#         "module_dependency_resolver",
#         "structure_normalizer",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/types/strings/observers/converting:lib",
#     ],
# )

# hcp(
#     name = "structure_normalizer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "casing_adjuster",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "greedy_reflower",
#     deps = [
#         "//code/utilities/types/strings/observers/splitting:words_deriver",
#         "//code/utilities/linguistics/grammar:grammar_adjuster",
#         "//code/utilities/linguistics/grammar/settings:comment_grammar_settings",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "knuth_plass_entry",
#     deps = [],
# )

# hcp(
#     name = "knuth_plass_reflower",
#     deps = [
#         "//code/utilities/types/strings/observers/splitting:words_deriver",
#         "//code/utilities/linguistics/grammar:grammar_adjuster",
#         "//code/utilities/linguistics/grammar/settings:comment_grammar_settings",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )
