package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

hcp(
    name = "center_buttons",
    deps = [],
)

hcp(
    name = "joystick",
    deps = [],
)

hcp(
    name = "left_arrows",
    deps = [],
)

hcp(
    name = "right_buttons",
    deps = [],
)

hcp(
    name = "top_buttons",
    deps = [],
)
