# Flame graph success with:
# debug build
# perf record --call-graph dwarf ./main
# ./hotspot-v1.2.0-x86_64.AppImage

# other notes:
# had trouble getting perf to actually work because of a missing kernel package.
# just build perf from scratch instead:

# git clone https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
# cd linux/tools/perf
# make
# cp perf /usr/bin
