package(default_visibility = ["//visibility:public"])


hcp(
    name = "boilerplate_printer",
    deps = [
        "//code/tools/transcompilers/old_unilang/boilerplate_printer:code_wrap_printer",
        "//code/tools/transcompilers/old_unilang/boilerplate_printer:include_guard_wrap_printer",
        "//code/utilities/linguistics/computer/frontends/parts/extern_c:extern_wrap_printer",
        "//code/utilities/linguistics/computer/frontends/parts/header/impl:header_printer",
        "//code/tools/transcompilers/old_unilang/boilerplate_printer/meta_block:meta_block_printer",
        "//code/tools/transcompilers/old_unilang/options/language-specific/c:c_export_settings",
        "//code/tools/transcompilers/old_unilang/structure/model:structure",
        "//code/tools/transcompilers/old_unilang/structure/print/export_file_settings",
        "//code/utilities/linguistics/computer:source_language",
    ],
)
