#!/usr/bin/env bash
# If you're developing software in unilang, 
# this is the front-end script to build everything.
# We provide it as a convenience.  
# It shows the cononical way to build everything in the repository.  
# It also allows us to tweak the build command if necessary
# and only build what we consider to be "everything".
# It's also shorter and abstracted away from the particular build system used.
# Consider using user_build specifically when iterating in development.  
set -euo pipefail
./user_build build --keep_going --verbose_failures --cxxopt='--std=c++17' //...:all
