#!/usr/bin/env bash
# If you're developing software in unilang, 
# this is the front-end script to build everything.
# We provide it as a convenience.  
# It shows the cononical way to build everything in the repository.  
# It also allows us to tweak the build command if necessary
# and only build what we consider to be "everything".
# Although, I fully intend "everything" to stay what bazel considers "all".
# It's also shorter and abstracted away from the particular build system used.
# In theory, we could change the underlying build system,
# without changing the way this script is called.
set -euo pipefail
./user_build //...:all
