#!/usr/bin/env bash
# bazel_wrapper is a bootrapping bazel with no extra strings attached.
# This script provides a few extra (and necessary) flags.  
# Ideally, I would like calling bazel_wrapper directly to work when building the whole repo.
# The goal would be to have this script vall bazel_wrapper directly with no extra flags.
# Until I figure out how to set the correct default flags, there may be some extra flags
# automatically added here  

# toolchains to try:
# --crosstool_top=@co_vsco_bazel_toolchains//tools/cpp:default-toolchain
# --crosstool_top=@llvm_toolchain//:toolchain
#--noshow_progress \

# quiet vs loud on errors:
# --verbose_failures

#--keep_going \

#--sandbox_debug
set -euo pipefail

#--sandbox_debug \
#--verbose_failures \

#--sandbox_debug \
#--verbose_failures \
#--toolchain_resolution_debug \

#--strategy=CppLink=standalone \
#--strategy=CppCompile=standalone \

#--experimental_allow_tags_propagation \

./bazel_wrapper \
build \
--sandbox_debug \
--incompatible_bzl_disallow_load_after_statement=false \
--incompatible_no_transitive_loads=false \
--incompatible_disable_crosstool_file=false \
--incompatible_disable_deprecated_attr_params=false \
--incompatible_use_python_toolchains=false \
--incompatible_strict_action_env=false \
--incompatible_use_specific_tool_files=false \
--crosstool_top=@llvm_toolchain//:toolchain \
"$@"
