load("//bazel/cookbook/cpp:main.bzl", "cpp_main")

package(
    default_visibility = ["//visibility:public"],
)

cpp_main(
    name = "basic",
    deps = [
        "//code/utilities/output/printers:lib",
        "//code/utilities/time/sleeping:lib",
    ],
)
