package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "function_body", deps = [
"//code/transcompilers/unilang/structure/sections/method/body/body-ast:root_body_element",
"@com_github_boost_variant//:variant",
])