package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "function_body", deps = [
"//code/transcompilers/unilang/structure/sections/method/body/body-ast:root_body_element"
])