package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "regular_body_comment", deps = [
"//code/transcompilers/unilang/parser/body_parser:body_token_value"
])

hcp(name = "warning_body_comment", deps = [
"//code/transcompilers/unilang/parser/body_parser:body_token_value"
])

hcp(name = "todo_body_comment", deps = [
"//code/transcompilers/unilang/parser/body_parser:body_token_value"
])

