package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "all_comparison_impl_schemes",
#     deps = [
#     ],
# )

# hcp(
#     name = "comparison_function_getter",
#     deps = [
#         "//code/utilities/language_basic/relational-operator:relational_operator",
#         "//code/utilities/language_basic/relational-operator:relational_operator_converter",
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#     ],
# )

# hcp(
#     name = "comparison_impl_scheme",
#     deps = [
#         "//code/utilities/language_basic/relational-operator:relational_operator",
#     ],
# )
