package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "java_test_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/linguistics/grammar:grammar_adjuster",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/types/char:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/vectors/converters:lib",
#         "//code/utilities/types/vectors/observers:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp(
#     name = "java_test_str_getter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/converting:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/vectors/converters:lib",
#         "//code/utilities/types/vectors/observers:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp(
#     name = "java_test_settings_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/meta/settings/organizations:organization",
#         "//code/utilities/personal/life:company_getter",
#         "//code/utilities/program/common_actions/exits:lib",
#     ],
# )
