package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="rgb_color",deps = [])
hcp(name="transparent_rgb_color",deps = [])
hcp(name="hsv_color",deps = [])
hcp(name="transparent_hsv_color",deps = [])