package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="multi_color_bitmap", deps = [
"//code/utilities/graphics/imgui/ui/draw/bitmap/pixel:pixel_settings",
])