package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:hcp.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "attribute_style_to_string_converter", deps = [
"//code/transcompilers/unilang/options/sections/method/attributes/specific/parts:attribute_style",
])