package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "attribute_style_to_string_converter", deps = [
"//code/transcompilers/unilang/options/sections/method/attributes/specific/parts:attribute_style",
])