#!/usr/bin/env zsh
git stash;
BRANCH_NAME=`echo "$@" | tr ' ' '_' | tr -d '(' | tr -d ')'`
arc flow $BRANCH_NAME
git stash pop;
git add -A :/
create_commit_file "$@"
arc diff -a -m "$@" --nolint -F ~/Desktop/commit_test
#create_next_branch