package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "enum_section", deps = [
"//code/transcompilers/unilang/structure/sections/enum/item:enum_item",
])