#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#called from the root of a cold fusion web repo,
#this command will open up sublime with only the files that are important for the programmer to edit
#The command opens up everything, and then I just append on the files that I don't care about.
#It helps avoid clutter, and if I really do need to look at these files for some reason, I can always drag them in

subl -n `ls | sed -e 's/dist//g' | sed -e 's/bower_components//g' | sed -e 's/node_modules//g' | sed -e 's/package.json//g' | sed -e 's/bower.json//g' | sed -e 's/config.xml.cfm//g'`