package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "protobuf_exporter",
#     deps = [
#         "//code/tools/transcompilers/old_unilang/boilerplate_printer",
#         "//code/tools/transcompilers/old_unilang/boilerplate_printer:code_wrap_printer",
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/protobuf:protobuf_options_getter",
#         "//code/tools/transcompilers/old_unilang/enum_printer:enum_section_printer",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler:file_transferer",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_settings",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_transfer_action",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_transferer",
#         "//code/utilities/linguistics/computer/frontends/protobuf/settings:protocol_buffer_export_settings",
#         "//code/tools/transcompilers/old_unilang/structure/adjust:structure_adjuster",
#         "//code/tools/transcompilers/old_unilang/structure/model:structure",
#         "//code/tools/transcompilers/old_unilang/structure/model/sections/meta:code_type",
#         "//code/tools/transcompilers/old_unilang/structure/print:file_printer",
#         "//code/tools/transcompilers/old_unilang/structure/print:namespace_printer",
#         "//code/tools/transcompilers/old_unilang/structure/print:stream_creator",
#         "//code/tools/transcompilers/old_unilang/structure/print:struct_printer",
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/tools/transcompilers/old_unilang/structure/print/filename:file_name_getter",
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl:header_printer",
#         "//code/utilities/types/char:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/other:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "protobuf_options_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/protobuf/settings:protocol_buffer_export_settings",
#         "//code/tools/transcompilers/old_unilang/structure/model:structure",
#         "//code/utilities/linguistics/computer/frontends/parts/meta/settings/organizations:organization",
#         "//code/utilities/personal/life:company_getter",
#         "//code/utilities/program/common_actions/exits:lib",
#     ],
# )
