package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "ur_dice",
    deps = [
        "//code/utilities/random/dice:n_sided_dice"
    ]
)