package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "enum_subgroup_affiliation_function_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/inflection:inflection_converter",
#         "//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
#         "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
#     ],
# )
