load("//bazel/cookbook/cpp:main.bzl", "cpp_main")
package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "key_press",
    srcs = ["key_press.cpp"],
    linkopts = ["-lncurses"],
    deps = [],
)