package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "scattergories_categories", deps = [
    "//code/utilities/types/vectors/transformers:lib",
    "//code/utilities/language_basic/std_hackery:std_aliases",
])