package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "scattergories_categories",
    deps = [
        "//code/utilities/language_basic/std_hackery:std_aliases",
        "//code/utilities/types/vectors/transformers:lib",
    ],
)
