package(
    default_visibility = ["//visibility:public"],
)

sh_test(
    name = "main",
    #tags = ["block-network"],
    exec_properties = {"block-network" :"true", "debug-before-execution" : "true"},
    srcs = ["main.sh"],
)
