package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/unilang:generate_unilang_token_files.bzl", "generate_unilang_token_files")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "token_builder",
    deps = [
        "//code/tools/transcompilers/unilang/tokens:all_language_tokens",
        "//code/tools/transcompilers/unilang/tokens:token_name",
        "//code/utilities/types/converters:lib",
    ],
)
