package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "contributor", deps = [
"//code/tools/transcompilers/unilang/contributor/names:contributor_names",
"//code/tools/transcompilers/unilang/contributor/appearance:contributor_appearance",
"//code/tools/transcompilers/unilang/contributor/contact:contributor_contact_details",
"//code/tools/transcompilers/unilang/contributor/work_info:contributor_work_info",
])