package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp_hdrs_derive(
#     name = "enum_first_function_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp_hdrs_derive(
#     name = "enum_last_function_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp_hdrs_derive(
#     name = "enum_total_function_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )
