package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "comparison_function_build_settings",
#     deps = [
#     ],
# )

# hcp(
#     name = "data_member_utility_function_options",
#     deps = [
#         "comparison_function_build_settings",
#     ],
# )
