package(
    default_visibility = ["//visibility:public"],
)

# cc_binary(
#     name = "main",
#     srcs = ["main.cpp"],
#     linkopts = [
#         "-lGL",
#     ],
#     deps = [
#         "@GL",
#         "@x11",
#         "@glut",
#     ],
# )
