package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

cpp_object(name = "method_event_characteristic")

hcp(
    name = "method_inheritence_specifiers",
    deps = [
        "//code/tools/transcompilers/unilang/structure/model/sections:structure_enums",
    ],
)

hcp(
    name = "method_overload_specifiers",
    deps = [
        "//code/tools/transcompilers/unilang/structure/model/sections:structure_enums",
    ],
)
