package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "data_member_manipulation_settings", deps = [
"//code/transcompilers/unilang/options/manipulation:comment_adjustment_settings"
])