package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:main.bzl", "cpp_main")   

hcp(name = "puyo", deps = [] ,data = ["@PuyoPuyoAssets//:all"])
hcp(name = "english_sounds", deps = [] ,data = ["@english_sounds//:all"])