package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "value_transition_meaning",
#     deps = [
#         "data_member_transition_state",
#     ],
# )

# hcp(
#     name = "data_member_transition_state",
#     deps = [
#     ],
# )
