package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "code_graph",
#     deps = [
#         "//code/utilities/data_structures/graph/unique_vertex_graph:lib",
#     ],
# )

# hcp(
#     name = "seen_structure_dependencies",
#     deps = [
#     ],
# )

# hcp(
#     name = "dependency_graph_creator",
#     deps = [
#         "//code/utilities/types/sets:lib",
#     ],
# )

# hcp(
#     name = "dependency_looker_upper",
#     deps = [
#         "//code/utilities/filesystem/files/observers/lstat_wrap:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )
