#!/usr/bin/env zsh
prepare-context thickey-mini-almono;

#spawn
source/mlp/tools/airflow-mlp/scripts/trigger-dag.sh thickey-mini-almono-mint_full_map_build /mnt/map_prod/transient/process/mint_integ_mapbuild/almono_mini/triggers/thickey_trigger_example.json "thickey-mini-almono"