package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "interval_inclusion_type")

# hcp(
#     name = "interval_constraint",
#     deps = [
#     ],
# )

# hcp(
#     name = "interval_point",
#     deps = [
#     ],
# )
