package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "int", deps = [
    "//code/utilities/types/converters:lib",
    "//code/utilities/types/strings/observers/converting:lib",
])
