package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "int",
    deps = [
        "//code/utilities/types/converters:lib",
        "//code/utilities/types/strings/observers/converting:lib",
    ],
)
