#!/usr/bin/env zsh
COMMIT_FILE="$HOME/Desktop/commit_test"
USERS="@mgoldman @oebelingkoning"
echo "$@" > $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo -n "Summary: " >> $COMMIT_FILE
echo "$@" >> $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo "Test Plan:" >> $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo -n "Reviewers: " >> $COMMIT_FILE
echo $USERS >> $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo "Subscribers:" >> $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo "Release Notes:" >> $COMMIT_FILE
echo "" >> $COMMIT_FILE
echo -n "Release Products:" >> $COMMIT_FILE