#!/usr/bin/env zsh

# Update the system, in case any new depenencies are needed
sudo apt-get update;
sudo apt-get install -y uberatc-dev;
sudo apt-get install -y uberatc-core;
sudo apt-get install -y uberatc-platform-generic;
sudo apt-get install -y uberatc-platform-keyring;
sudo apt-get install -y uberatc-platform-generic;
sudo apt-get install -y uberatc-platform-fileservers;
sudo apt-get install -y uberatc-platform-precision-tower-7910;
sudo apt-get install -y uberatc-platform-printers;
sudo apt-get install -y uberatc-platform-security;
sudo apt-get install -y uberatc-platform-security-certificates;
sudo apt-get install -y uberatc-platform-wireless;
sudo apt-get install -y --upgrade uberatc-platform-generic;

#Anthony Olive had everybody update hardware specific driver packages...
#but I never did it.  later he consolidated it:
sudo apt-get install uberatc-platform-workstation;




#Other packages that are maybe related and important to have
#--------------
sudo apt-get install -y extlinux;
sudo apt-get install -y qemu-system-x86;
sudo apt-get install -y qgis;
sudo apt-get install -y meshlab;

#should I ever try to reinstall?
#this was suggested when running into an error
#for now, I think its best to not do that. 
#especially not every morning
#sudo apt-get install --reinstall uberatc-dev;
#sudo apt-get install --reinstall uberatc-platform-generic;