package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "namespace_options",
deps = ["//code/utilities/types/strings/transformers/casing:case_format_style"
])