package(default_visibility = ["//visibility:public"])

load("//bazel/rules/unilang:transfer_unilang_java.bzl", "transfer_unilang_java")

transfer_unilang_java("determinism_check_settings", "/home/luxe/Desktop/repos/bazel-buildfarm/src/main/java/build/buildfarm/worker/determinism/DeterminismCheckSettings.java")

transfer_unilang_java("determinism_check_results", "/home/luxe/Desktop/repos/bazel-buildfarm/src/main/java/build/buildfarm/worker/determinism/DeterminismCheckResults.java")

transfer_unilang_java("determinism_checker", "/home/luxe/Desktop/repos/bazel-buildfarm/src/main/java/build/buildfarm/worker/determinism/DeterminismChecker.java")
