package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="gcal_getter", deps = [
    "//code/utilities/shell:lib",
    "//code/utilities/web:lib",
    "//code/utilities/types/strings/observers/other:lib",
])