package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "regular_body_comment",
#     deps = [
#     ],
# )

# hcp(
#     name = "warning_body_comment",
#     deps = [
#     ],
# )

# hcp(
#     name = "todo_body_comment",
#     deps = [
#     ],
# )
