#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#downloads a repo using git-it, steps into it, and opens it in sublime
git-it $1; cd `repo_url_parser $1 --repo-name`; cd project/src/; subl -n Sub/;
