load("//bazel/rules/cpp:main.bzl", "cpp_main")
load("//bazel/rules/protobuf:cpp.bzl", "cpp_proto_object")

package(
    default_visibility = ["//visibility:public"],
)

cpp_proto_object(
    name = "build_plan",
)
