#!/usr/bin/env zsh
source ~/.oh-my-zsh/custom/alias.zsh

#move
go-to-main-repo;

#make
make-all;

#setup
sudo expect -c "set timeout -1; spawn source/mlp/tools/airflow-mlp/scripts/setup-context.py $@ --email thickey@uber.com; expect \"Please enter numbers of dags to activate (separated by space): \"; send -- \"12\r\"; expect eof"

#mount
./cops --cluster CORNDOG mount_context $@;

#sync
./cops --cluster CORNDOG sync_context_in_parallel $@;