#!/usr/bin/env zsh
prepare-context thickey-micro-almono-nightly-1;

#spawn
source/mlp/tools/airflow-mlp/scripts/trigger-dag.sh thickey-micro-almono-nightly-1-mint_full_map_build /mnt/map_prod/transient/process/mint_integ_mapbuild/almono_mini/triggers/thickey_trigger_micro_nightly_1_example.json "nightly-micro-almono-1"