#!/usr/bin/env zsh
source ~/.oh-my-zsh/custom/alias.zsh
echo "CREATING CONTAINER:"
./rops release context create --push 2>&1

echo "GETTING CONTAINER NAME:"
CONTAINER_NAME=`./rops release context create --push 2>&1 | grep "^atg"`
echo $CONTAINER_NAME

#copy over pipeline
cp -R /home/thickey/Desktop/piper-pipelines/atc/avmaps/pipelines/workflow/map_build /mnt/home0/services/piper/staging_pipelines/atc/thicke