package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "moded_index",
    deps = [
        "//code/utilities/data_structures:index_mode",
    ],
)
