package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp_hdrs_derive(
#     name = "enum_to_str_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/inflection:inflection_converter",
#         "//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
#         "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
#     ],
# )

# hcp_hdrs_derive(
#     name = "enum_to_str_inflection_count_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/inflection:inflection_converter",
#         "//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
#         "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
#     ],
# )

# hcp_hdrs_derive(
#     name = "enum_to_str_plural_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/inflection:inflection_converter",
#         "//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
#         "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
#     ],
# )

# hcp_hdrs_derive(
#     name = "enum_to_str_singular_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/enum:enum_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/inflection:inflection_converter",
#         "//code/utilities/types/strings/transformers/inflection/getters:inflection_settings_getter",
#         "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
#     ],
# )
