package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name="extern_c_guard_options", deps = [
"//code/transcompilers/unilang/options/sections/extern_c/guard_sections:begin_extern_c_guard_options",
"//code/transcompilers/unilang/options/sections/extern_c/guard_sections:end_extern_c_guard_options",
])