#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#Remove files that end in a '~' recursively from my Desktop directory
find ~ -name '*~' -exec rm '{}' \; -print -or -name ".*~" -exec rm {} \; -print
