package(
    default_visibility = ["//visibility:public"],
)

load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

enum_cpp(
    name = "tri_state_switch",
    values = [
        "low",
        "middle",
        "high",
    ],
)
