package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "contributor", deps = [
"//code/transcompilers/unilang/contributor/names:contributor_names",
"//code/transcompilers/unilang/contributor/appearance:contributor_appearance",
"//code/transcompilers/unilang/contributor/contact:contributor_contact_details",
"//code/transcompilers/unilang/contributor/work_info:contributor_work_info",
])