#!/usr/bin/env zsh

gconftool --recursive-unset /apps/panel

#if the first time doesn't work, and you run it again, it tends to crash the whole system and log you out.  
#not sure why that happens.  gnome and ubuntu are probably just hacky garbage. (plus we aren't on the latest ubuntu)
#Maybe wait a min before running the script
#(asssuming the gnome panel was missing when you logged in)
#not sure why the panel is missing in the first place when you log on.. need to look into fixing that
#
#Update: seriously look into this when you have time.  its really annoying on reboots.  
#And sometimes doesn't work, causing the system to log out on the second attempt

#this seemed to work
gconftool-2 --shutdown
rm -rf ~/.gconf/apps/panel
pkill gnome-panel