
# cc_binary(
#     name = "annotation_tool_summary",
#     srcs = ["annotation_tool_summary.cc"],
#     deps = [
#     "//code/utilities/shell:lib",
#     "//code/utilities/peripheral/mouse:mouse_controller",
#     ],
#     linkopts = ["-lXcursor", "-lxdo"],
# )