package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "template_section",
#     deps = [
#         "//code/tools/transcompilers/old_unilang/parser:token_value",
#         "//code/tools/transcompilers/old_unilang/structure/model/sections/method/arguments/argument:template_argument",
#     ],
# )
