package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "methods_adjuster",
#     deps = [
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )
