package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "method_chaining_enforcer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "method_overload_adjuster",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "return_statement_enforcer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "immutable_value_to_immutable_ref_adjuster",
#     deps = [
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "instantiate_and_return_injector_for_return_type",
#     deps = [
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/char:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/variant:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "function_unit_test_name_defaulter",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "methods_sorter",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )
