package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "argument_direction_decider",
#     deps = [
#         "//code/utilities/comments/doxygen/maker:doxygen_data_shared",
#         "//code/utilities/comments/doxygen/settings:doxygen_parameter_direction",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#     ],
# )

# hcp(
#     name = "closed_box_function_checker",
#     deps = [
#         "//code/utilities/code/query:argument_direction_decider",
#         "//code/utilities/comments/doxygen/settings:doxygen_parameter_direction",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#     ],
# )

# hcp(
#     name = "is_overload_decider",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "duplicated_type_information_with_parent_checker",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "duplicated_identifier_information_with_parent_checker",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "virtual_method_checker",
#     deps = [
#     ],
# )

# hcp(
#     name = "mock_test_checker",
#     deps = [
#     ],
# )

# hcp(
#     name = "redis_test_checker",
#     deps = [
#     ],
# )
