package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "file_extension_getter", deps = [
"//code/transcompilers/unilang/type_converters/unilang-type-to-language-type-converter/languages:source_language",
"//code/transcompilers/unilang/file_extension_getter/lookup_table:file_extension_lookup_table_getter",
"//code/utilities/types/map:lib"
])