package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")

hcp(name = "sound", deps = [
])

hcp(name = "sounds", deps = [
    "//code/tools/mario/sound:sound",
])

hcp(name = "sounds_loader", deps = [
    "//code/tools/mario/sound:sounds",
])