package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "header_block_comment_getter", deps = [
"//code/tools/transcompilers/unilang/options/sections/import:shared_headers_block_comment",
"//code/tools/transcompilers/unilang/comment_creator:comment_creator",
])