package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "real_time_shadowing",
    hdrs = [
        "real_time_shadowing.hpp",
    ],
    srcs = ["real_time_shadowing.cpp","real_time_shadowing2.cpp"],
    deps = [
        "@x11",
        "@mesa_glu",
        "@glut",
    ],
)