package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "real_time_shadowing",
    srcs = [
        "real_time_shadowing.cpp",
        "real_time_shadowing2.cpp",
    ],
    hdrs = [
        "real_time_shadowing.hpp",
    ],
    deps = [
        "@glut",
        "@mesa_glu",
        "@x11",
    ],
)

cc_library(
    name = "sphere",
    srcs = ["sphere.cpp"],
    hdrs = ["sphere.hpp"],
    deps = [
        "@glut",
        "@mesa_glu",
        "@x11",
    ],
)
