package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "real_time_shadowing",
    hdrs = [
        "real_time_shadowing.hpp",
    ],
    srcs = ["real_time_shadowing.cpp",],
)