#!/usr/bin/env bash


# doesn't quite do what I want as it turns all feature branches into regularly named branches
for branch in `git branch -a | grep remotes | grep -v HEAD`; do
    git branch --track ${branch##*/} $branch
done
