package(
    default_visibility = ["//visibility:public"],
)

filegroup(
          name = "data",
          srcs = ["isosurf.dat"],
)

# cc_binary(
#     name = "main",
#     srcs = ["main.cpp"],
#     linkopts = [
#         "-lGL",
#     ],
#     deps = [
#         "@x11",
#         "@glut",
#     ],
# 	data = [":data"],
# )
