package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")
load("//bazel/cookbook/hcp:hcp_and_hcp_pos.bzl", "hcp_and_hcp_pos")

hcp(
    name = "int_tree",
    deps = [
        "@tree",
    ],
)

hcp(
    name = "string_tree",
    deps = [
        "@tree",
    ],
)
