package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "test_wrapper_utilities",
#     deps = [
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "va_list_part_getter",
#     deps = [
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "wrapper_interface_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "wrapper_source_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "in_out_design_test_wrapper_printer",
#     deps = [
#         "wrapper_interface_printer",
#         "wrapper_source_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "normal_design_test_wrapper_printer",
#     deps = [
#         "wrapper_interface_printer",
#         "wrapper_source_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "test_wrapper_alias_helper_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "test_wrapper_method_shared",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "test_wrapper_methods_printer",
#     deps = [
#         "va_list_part_getter",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "test_wrapper_printer",
#     deps = [
#         "in_out_design_test_wrapper_printer",
#         "normal_design_test_wrapper_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/comparing:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "test_wrapper_special_method_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )
