package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "reflexive_refresh_settings", deps = [
])

hcp(name = "reflexive_refresh_settings_getter", deps = [
    "//code/tools/reflexivity/settings:reflexive_refresh_settings"
])
