package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "reflexive_refresh_settings",
    deps = [
    ],
)

hcp(
    name = "reflexive_refresh_settings_getter",
    deps = [
        "//code/tools/reflexivity/settings:reflexive_refresh_settings",
    ],
)
