package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "identifier_notation_settings",deps = [
"//code/transcompilers/unilang/options/hungarian/characteristic:hungarian_characteristic_settings",
"//code/transcompilers/unilang/options/hungarian/type:hungarian_type_settings",
])