package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "value_constraints_to_interval_constraints",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/char:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#         "//code/utilities/types/wstrings/transformers/other:lib",
#     ],
# )

# hcp(
#     name = "concise_constraint_exporter",
#     deps = [
#         "//code/utilities/comments/doxygen/maker:doxygen_block_maker",
#         "//code/utilities/comments/doxygen/maker:doxygen_data",
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/files/transformers:lib",
#         "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "concise_constraint_line_exporter",
#     deps = [
#         "value_constraints_to_interval_constraints",
#         "//code/utilities/comments/doxygen/maker:doxygen_block_maker",
#         "//code/utilities/comments/doxygen/maker:doxygen_data",
#         "//code/utilities/contributor",
#         "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "if_chain_constraint_exporter",
#     deps = [
#         "//code/utilities/comments/doxygen/maker:doxygen_block_maker",
#         "//code/utilities/comments/doxygen/maker:doxygen_data",
#         "//code/utilities/contributor",
#         "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "constraint_exporter",
#     deps = [
#         "//code/utilities/contributor",
#     ],
# )
