package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:hcp.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "function_call_local", deps = [
"//code/transcompilers/unilang/parser/body_parser:body_token_value"
])