package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "sentence_table",
#     deps = [
#         ":sentence_table_header",
#         ":sentence_table_row",
#     ],
# )

# hcp(
#     name = "sentence_table_header",
#     deps = [
#     ],
# )

# hcp(
#     name = "sentence_table_row",
#     deps = [
#     ],
# )
