package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "code_type")

# hcp(
#     name = "foreseeable_change",
#     deps = [
#     ],
# )

# hcp(
#     name = "meta_subgroup",
#     deps = [
#     ],
# )

# hcp(
#     name = "specification_file",
#     deps = [
#     ],
# )

# hcp(
#     name = "meta_section",
#     deps = [
#         "foreseeable_change",
#         "meta_subgroup",
#         "specification_file",
#     ],
# )
