package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "implicit_global_header_comment_deriver",
#     deps = [
#     ],
# )

# hcp(
#     name = "header_collector",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/comments/code:comment_creator",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl:implicit_global_header_comment_deriver",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl/relationships:import_relationship_comment_deriver",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl/unilang-convert:header_extension_deriver",
#         "//code/utilities/types/sets:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "header_printer",
#     deps = [
#         "//code/utilities/comments/code:comment_creator",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl:header_collector",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl/block:header_block_comment_getter",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl/unilang-convert:header_adjuster",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )
