package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "namespace_options",
    deps = [
        "//code/utilities/types/strings/transformers/casing:case_format_style",
    ],
)
