package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "type_item", deps = [
"//code/transcompilers/unilang/parser:token_value"
])

hcp(name = "type_section", deps = [
"type_item"
])