load("//bazel/cookbook:hcp.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")
package(default_visibility = ["//visibility:public"])

cpp_object(name = "tree")
cpp_object(name = "tree_util", deps = ["tree"])