package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "structure_name_kind")

# hcp(
#     name = "struct_name_deriver",
#     deps = [
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "type_name_deriver",
#     deps = [
#         "//code/utilities/linguistics/computer/types/cross/language_type",
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "structure_typename_deriver",
#     deps = [
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "identifier_name_deriver",
#     deps = [
#         "//code/utilities/linguistics/computer/types/self_describe_type:modify_identifier_with_extra_type_info",
#         "//code/utilities/linguistics/computer/frontends/parts:notation_settings",
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types:tri_bool",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/units:unit_suffix_lookuper",
#         "//code/utilities/units:units_to_variable_suffix_lookup_table",
#     ],
# )
