package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "regular_body_comment",
    deps = [
        "//code/tools/transcompilers/unilang/parser/body_parser:body_token_value",
    ],
)

hcp(
    name = "warning_body_comment",
    deps = [
        "//code/tools/transcompilers/unilang/parser/body_parser:body_token_value",
    ],
)

hcp(
    name = "todo_body_comment",
    deps = [
        "//code/tools/transcompilers/unilang/parser/body_parser:body_token_value",
    ],
)
