package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object("structure_enums")

# cpp_object("existence_reason")

# hcp(
#     name = "library_dependency",
#     deps = [
#     ],
# )

# hcp(
#     name = "module_dependency",
#     deps = [
#     ],
# )

# hcp(
#     name = "type_specialization",
#     deps = [
#     ],
# )
