package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")


hcp("rust_export_settings",deps = [
"//code/tools/transcompilers/unilang/options/manipulation:struct_manipulation_settings"
])