#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

cd ~/Desktop;

#reinstall font
if [ -d tokens ]; then 
	cd font/src;
	./re-install-font.zsh;
else 
   echo ~/Desktop/tokens does not exist;
   exit;
fi

cd ~/Desktop;

#update tokens
if [ -d tokens ]; then 
   cd tokens/project/src;
   make clean;
   git-it --clean --all;
   git-it --local-pulls --all;
   make;
   update;
else 
   echo ~/Desktop/tokens does not exist;
   exit;
fi

cd ~/Desktop;

#rebuild language and theme creator
#update tokens
if [ -d language-and-theme-creator ]; then 
   cd language-and-theme-creator/project/src;
   make clean;
   git-it --clean --all;
   git-it --local-pulls --all;
   make;
   update;
else 
   echo ~/Desktop/language-and-theme-creator/project/src does not exist;
   exit;
fi

cd ~/Desktop;

#run theme creator
cd /home/flighty/.config/sublime-text-3/Packages
unilang-language-and-theme-creator