#!/usr/bin/env bash

function Set_Uber_Credentials() {
	echo "Using Uber Credentials"
	git config user.email "thickey@uber.com"
	git config user.name "Trevor Hickey"
}
function Set_Personal_Credentials() {
	echo "Using Personal Credentials"
	git config user.email "TrevorJamesHickey@gmail.com"
	git config user.name "Trevor Hickey"
}

#get the url of the repo
REPO_URL=`repo_url`

#set our git credentials based on the repo url
if [ "$REPO_URL" == "ssh://code@code.int.uberatc.com/diffusion/AV/av.git" ]; then
	Set_Uber_Credentials
elif [ "$REPO_URL" == "ssh://code@code.int.uberatc.com/diffusion/SVCS/services.git" ]; then
	Set_Uber_Credentials
else
	Set_Personal_Credentials
fi
