load("//bazel/cookbook/cpp:main.bzl", "cpp_main")

package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = ["@xcb","@Xau"],
)

cc_binary(
    name = "main2",
    srcs = ["main2.cpp"],
    deps = ["@xcb","@Xau"],
)

cc_binary(
    name = "event",
    srcs = ["event.cpp"],
    deps = ["@xcb","@Xau"],
)
