package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "global")

# hcp(
#     name = "language_file_creator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "reference_file_creator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "settings_file_creator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "shared",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#     ],
# )

# hcp(
#     name = "stylized_reference_file_creator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#     ],
# )

# hcp(
#     name = "unilang_file_creator",
#     deps = [
#     ],
# )

# hcp(
#     name = "theme_file_creator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )
