#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#a better diff
git diff --minimal --patience --color-words="[^[:space:]]|([[:alnum:]]|UTF_8_GUARD)+"
