package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

cpp_object(name = "method_event_characteristic")

hcp(name = "method_inheritence_specifiers", deps = [
"//code/transcompilers/unilang/structure/sections:structure_enums"
])

hcp(name = "method_overload_specifiers", deps = [
"//code/transcompilers/unilang/structure/sections:structure_enums"
])