#!/usr/bin/env bash

#Case Formatters:
function Pushed_Caps_Case(){
      echo "$1" | tr _ " " | tr [A-Z] [a-z] | sed "s/\( \|^\)\(.\)/\1\u\2/g" | tr -d " "
}

#For printing nicely
function Caps_Case(){
  echo "$1" | tr _ " " | tr [A-Z] [a-z] | sed -r 's/\<./\U&/g';
}
