package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")

hcp(name = "moving_text", deps = [
    "@sfml//:sfml",
])

hcp(name = "named_rectangle", deps = [
    "@sfml//:sfml",
])

hcp(name = "named_rectangles", deps = [
    "@sfml//:sfml",
    "//code/utilities/graphics/sfml/data:named_rectangle",
])