package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "import_item",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "import_section",
#     deps = [
#         "import_item",
#     ],
# )

# cpp_object(name = "import_type")
