package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "function_table_of_contents_printer",
#     deps = [
#         "//code/tools/transcompilers/old_unilang/options/language-specific/c:c_export_settings",
#         "//code/tools/transcompilers/old_unilang/structure/model:structure",
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/other:lib",
#     ],
# )
