package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    "slidy_settings",
    deps = [
        "//code/tools/transcompilers/old_unilang/options:general_options",
        "//code/tools/transcompilers/old_unilang/options/language-specific/slidy:slidy_creation_settings",
        "//code/tools/transcompilers/old_unilang/options/manipulation:struct_manipulation_settings",
        "//code/utilities/linguistics/computer/frontends/markdown/settings:markdown_settings",
        "//code/utilities/linguistics/computer/frontends/parts:portion_options",
    ],
)

hcp(
    "slidy_creation_settings",
    deps = [
    ],
)
