package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(
    name = "all_argument_attribute_placements",
    deps = ["argument_attribute_placement"],
)

hcp(
    name = "all_method_attribute_placements",
    deps = ["method_attribute_placement"],
)

hcp(name = "argument_attribute_placement")

hcp(name = "method_attribute_placement")
