package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hcp-compiler",
    srcs = ["main.cpp"],
    deps = [
        "//code/tools/transcompilers/hcp-compiler/bootstrap/core",
        "//code/tools/transcompilers/hcp-compiler/bootstrap/program_options:lib",
        "//code/utilities/program/common_actions/locale:lib",
    ],
)
