package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lib",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),
    deps = ["//code/utilities/types/strings/observers/other:lib",
"//code/utilities/program/common_actions/exits:lib",
"//code/utilities/types/wstrings/transformers/other:lib",
"//code/utilities/types/strings/transformers/removing:lib",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/observers/char:lib",
],
)
