package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "program_input",
#     deps = [
#     ],
# )

# hcp(
#     name = "program_input_validator",
#     deps = [
#     ],
# )

# hcp(
#     name = "root_exception_handler",
#     deps = [
#
#         "@boost//:exception",
#         "@boost//:smart_ptr",
#         "@boost//:throw_exception",
#     ],
# )

# hcp(
#     name = "task_executer",
#     deps = [
#     ],
# )

# cc_binary(
#     name = "unilang-transcompiler",
#     srcs = ["main.cpp"],
#     deps = [
#     ],
# )
