package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "mermaid_graph_orientation")

# hcp(
#     "mermaid_settings",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts:portion_options",
#     ],
# )
