package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "xml_string_escaper",deps=[
    "//code/utilities/types/strings/transformers/search_replace:lib"
])
