package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "json_print_method_getter",deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/data_member:data_member_item",
"//code/tools/transcompilers/unilang/options/sections/data_member:data_member_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_data_member:data_member_utility_function_options",
"//code/tools/transcompilers/unilang/options/language-specific:c_language_version",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-comparison/settings:special_comparison_type",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call:json_function_name_getter",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call/settings:json_function_settings",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-json:special_type_json_specifier_getter",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/observers/other:lib",
"//code/utilities/types/strings/transformers/removing:lib",
"//code/utilities/types/vectors/operators:lib",
])

hcp(name = "to_json_method_getter",deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/data_member:data_member_item",
"//code/tools/transcompilers/unilang/options/sections/data_member:data_member_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_data_member:data_member_utility_function_options",
"//code/tools/transcompilers/unilang/options/language-specific:c_language_version",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-comparison/settings:special_comparison_type",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call:json_function_name_getter",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call/settings:json_function_settings",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-json:special_type_json_specifier_getter",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/observers/other:lib",
"//code/utilities/types/strings/transformers/removing:lib",
"//code/utilities/types/vectors/operators:lib",
])

hcp(name = "serialize_json_method_getter",deps = [
"//code/tools/transcompilers/unilang/structure/model/sections/data_member:data_member_item",
"//code/tools/transcompilers/unilang/options/sections/data_member:data_member_options",
"//code/tools/transcompilers/unilang/structure/model/sections/method:method_item",
"//code/tools/transcompilers/unilang/options/manipulation/methods/via_data_member:data_member_utility_function_options",
"//code/tools/transcompilers/unilang/options/language-specific:c_language_version",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-comparison/settings:special_comparison_type",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call:json_function_name_getter",
"//code/tools/transcompilers/unilang/type_converters/type-to-json-serialization-call/settings:json_function_settings",
"//code/tools/transcompilers/unilang/type_converters/special-type-to-json:special_type_json_specifier_getter",
"//code/tools/transcompilers/unilang/structure/model:structure",
"//code/utilities/types/converters:lib",
"//code/utilities/types/strings/observers/other:lib",
"//code/utilities/types/strings/transformers/removing:lib",
"//code/utilities/types/vectors/operators:lib",
])