package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "contributor_name")
hcp(name = "contributor_names", deps = [
"contributor_name"
])