package(
    default_visibility = ["//visibility:public"],
)

# cc_library(
#     name = "trackball",
#     hdrs = ["trackball.h"],
#     srcs = ["trackball.c"]
# )

# cc_binary(
#     name = "main",
#     srcs = ["main.cpp"],
#     linkopts = [
#         "-lGL",
#     ],
#     deps = [
#         "@x11",
#         "@glut",
#         ":trackball",
#     ],
# )
