package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:main.bzl", "cpp_main")   

hcp(name = "arial", deps = [] ,data = ["@fonts//:Arial"])
hcp(name = "droid_sans_mono", deps = [] ,data = ["@fonts//:DroidSansMono"])