package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:main.bzl", "cpp_main")

hcp(
    name = "eight_bit_wonder",
    data = ["@fonts//:eight_bit_wonder"],
    deps = [],
)

hcp(
    name = "pixel_bit_advanced",
    data = ["@fonts//:pixel_bit_advanced"],
    deps = [],
)

hcp(
    name = "arial",
    data = ["@fonts//:Arial"],
    deps = [],
)

hcp(
    name = "droid_sans_mono",
    data = ["@fonts//:DroidSansMono"],
    deps = [],
)
