package(
    default_visibility = ["//visibility:public"],
)

#cc_binary(
#    name = "main",
#    srcs = ["main.cpp"],
#    #linkopts = ["-lSDL2"],
#    deps = ["@SDL2//:SDL2"],
#)

#"@SDL2//:lib/x84/SDL2main.lib"
