package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "existing_import_adjuster",
#     deps = [
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )

# hcp(
#     name = "import_adjuster",
#     deps = [
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/sets:lib",
#     ],
# )
