package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "f2si_c_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "f2si_contributors_getter",
#     deps = [
#         "//code/utilities/contributor",
#     ],
# )

# hcp(
#     name = "f2si_c_options_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/meta/settings/organizations:organization",
#         "//code/utilities/program/common_actions/exits:lib",
#     ],
# )

# hcp(
#     name = "uber_contributors_getter",
#     deps = [
#         "//code/utilities/contributor",
#     ],
# )

# hcp(
#     name = "bazel_options_getter",
#     deps = [
#         "//code/utilities/personal/life:company_getter",
#     ],
# )

# hcp(
#     name = "file_transferer",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/system:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "file_transfer_settings_getter",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/system:lib",
#     ],
# )
