package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "forward_declare_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )
