package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "method_names_section",
#     deps = [
#         "alternative_expression_name",
#     ],
# )

# hcp(
#     name = "alternative_expression_name",
#     deps = [
#     ],
# )
