package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(name = "switch_case_statement")

# hcp(
#     name = "switch_block",
#     deps = [
#     ],
# )

# hcp(
#     name = "switch_block_printer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )
