package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "acronyms",
    deps = [
        "//code/utilities/linguistics/acronyms/data:acronym",
    ],
)

hcp(
    name = "acronym",
    deps = [
    ],
)
