package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "plant_uml_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/files/observers/lstat_wrap:lib",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/comparing:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(name = "composition_relationship")

# hcp(
#     name = "plant_uml_options_getter",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/system:lib",
#     ],
# )

# hcp(
#     name = "plant_uml_customizations",
#     deps = [
#         "//code/utilities/types/strings/transformers/appending:lib",
#     ],
# )
