#!/usr/bin/env bash
set -e

if [ `hostname` = "thickey-5820" ]; then

    # make sure code is good.
    lat fix;

    # commit all changes in the repo.
    git add -A :/;
    git commit -am "updates" > /dev/null 2>&1;

    # merge with main.
    git pull origin main;

    # update to single commit on PR.
    squash-branch;

    # Automate the comment stuff.
    gh pr comment `git rev-parse --abbrev-ref HEAD` --repo nusqas1-s-ghe-01.fne.argo.ai/argoai/l3 -b "build me please"
    gh pr comment `git rev-parse --abbrev-ref HEAD` --repo nusqas1-s-ghe-01.fne.argo.ai/argoai/l3 -b "r+"
fi

#do a commit
up $@;
git push;
