#!/usr/bin/env bash
set -e

if [ `hostname` = "thickey-5820" ]; then

    # make sure code is good.
    lat fix;

    # commit all changes in the repo.
    git add -A :/;
    git commit -am "updates";

    # merge with main.
    git pull origin main;
    git merge main;

    # update to single commit on PR.
    squash-branch;
fi

#do a commit
up $@;
git push;
