package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(
    name = "enum_section",
    deps = [
        "//code/tools/transcompilers/unilang/structure/model/sections/enum/item:enum_item",
    ],
)
