package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "special_type_comparison_getter",
#     deps = [
#         "//code/utilities/language_basic/relational-operator:relational_operator_converter",
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )
