load("@rules_fuzzing//fuzzing:cc_defs.bzl", "cc_fuzz_test")

cc_fuzz_test(
    name = "fuzz_example",
    srcs = ["fuzz_example.cpp"],
)

cc_fuzz_test(
    name = "find_trap",
    srcs = ["find_trap.cpp"],
)
