package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "treesheets_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/vectors/observers:lib",
#     ],
# )
