package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(
    name = "function_call_local",
    deps = [
        "//code/tools/transcompilers/unilang/parser/body_parser:body_token_value",
    ],
)
