package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "regular_statement",
#     deps = [
#     ],
# )

# hcp(
#     name = "return_statement",
#     deps = [
#     ],
# )

# hcp(
#     name = "uncaught_statement",
#     deps = [
#     ],
# )
