package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "function_argument", deps = [
"//code/transcompilers/unilang/parser:token_value",
"//code/transcompilers/unilang/structure/sections/method/arguments:usage_requirement",
"//code/transcompilers/unilang/structure/sections:type_specialization",
])

hcp(name = "function_result", deps = [
"//code/transcompilers/unilang/parser:token_value",
"//code/transcompilers/unilang/structure/sections/method/arguments:usage_requirement",
"//code/transcompilers/unilang/structure/sections:type_specialization",
])

hcp(name = "template_argument", deps = [
"//code/transcompilers/unilang/parser:token_value",
"//code/transcompilers/unilang/structure/sections/method/arguments:usage_requirement"
])