package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(name = "printf_specifier")

# hcp(
#     name = "printf_specifier_settings",
#     deps = [
#     ],
# )

# hcp(
#     name = "individual_printf_specifier_getter",
#     deps = [
#     ],
# )
