package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "data_member_manipulation_settings", deps = [
"//code/tools/transcompilers/unilang/options/manipulation:comment_adjustment_settings"
])