package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(name = "dependency_paths")

hcp(
    name = "user_chosen_export_settings",
    deps = [
        "//code/tools/transcompilers/unilang/options/compiler:chosen_exporter",
        "//code/utilities/formats/artifact:artifact_type",
    ],
)
