package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "safe_queue",
    hdrs = ["safe_queue.h"],
    deps = [
    ]
)

cc_library(
    name = "finishable_safe_queue",
    hdrs = ["finishable_safe_queue.h"],
    deps = [
    ]
)
