cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = [
        "//code/utilities/peripheral/mouse:mouse_controller",
        "@xorg_libXcursor",
    ],
    #linkopts = ["-lXcursor", "-lxdo"],
)
