package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "posix_1_2001_example",
    srcs = ["posix_1_2001_example.cpp"],
    hdrs = ["posix_1_2001_example.hpp"],
    deps = [
    ],
)

cc_library(
    name = "mwc1616",
    srcs = ["mwc1616.cpp"],
    hdrs = ["mwc1616.hpp"],
    deps = [
    ],
)

cc_library(
    name = "xorshift128plus",
    srcs = ["xorshift128plus.cpp"],
    hdrs = ["xorshift128plus.hpp"],
    deps = [
    ],
)

