package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "posix_1_2001_example",
    srcs = ["posix_1_2001_example.cpp"],
    hdrs = ["posix_1_2001_example.hpp"],
    deps = [
    ],
)
