#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#gives back the name of the branch [example: `master`  or `feature`]
git rev-parse --abbrev-ref HEAD