package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "method_event_characteristic")

# hcp(
#     name = "method_inheritence_specifiers",
#     deps = [
#     ],
# )

# hcp(
#     name = "method_overload_specifiers",
#     deps = [
#     ],
# )
