package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lib",
    srcs = ["lib.cpp"],
    hdrs = ["lib.hpp"],
)

cc_library(
    name = "std_aliases",
    hdrs = ["std_aliases.hpp"],
)
