#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

if [ $# == 0 ]
then
expect -c "set timeout -1; spawn arc diff -m \"rebase\" --nounit --skip-staging --excuse \"queueing\" --nolint; expect \"*without these staging refs. Continue anyway?*\"; send -- \"y\r\"; expect eof"
else
expect -c "set timeout -1; spawn arc diff -m \"rebase\" --nounit --skip-staging --excuse \"queueing\" --nolint \"$@\"; expect \"*without these staging refs. Continue anyway?*\"; send -- \"y\r\"; expect eof"
fi