package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "object_to_counted_objects",
    deps = [
        "//code/utilities/linguistics/counted_object:counted_object",
    ],
)
