package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "inflection_converter",
    deps = [
        "//code/utilities/types/strings/transformers/inflection/settings:inflection_settings",
    ],
)
