package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "bazel_build_object")

# hcp(
#     name = "bazel_load_data",
#     deps = [
#     ],
# )

# hcp(
#     name = "bazel_load_db_settings",
#     deps = [
#     ],
# )

# hcp(
#     name = "build_rule_settings",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts:portion_options",
#     ],
# )

# hcp(
#     name = "language_to_build_object",
#     deps = [
#         "//code/utilities/formats/artifact:artifact_type",
#     ],
# )
