package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "data_member_utility_function_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#     ],
# )
