package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "function_test_case", deps = [
"//code/transcompilers/unilang/structure/unit_tests:test_section",
"//code/transcompilers/unilang/parser:token_value"
])