<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict><key>fileTypes</key><array>
<string>UniLang</string></array>
<key>name</key><string>UniLang</string><key>patterns</key><array>
<dict><key>begin</key><string>􏶴</string><key>end</key><string>􏶳</string><key>name</key><string>FUNCTION_BODY</string><key>patterns</key><array>
<dict><key>match</key><string>􏵱</string><key>name</key><string>TRUE_MACRO_IN_BODY</string></dict>
<dict><key>match</key><string>􏵰</string><key>name</key><string>FALSE_MACRO_IN_BODY</string></dict>
<dict><key>begin</key><string>􏶲</string><key>end</key><string>􏶱</string><key>name</key><string>COMMENT</string></dict>
<dict><key>begin</key><string>􏴕</string><key>end</key><string>􏴖</string><key>name</key><string>STATEMENT</string></dict>
<dict><key>begin</key><string>􏵶</string><key>end</key><string>􏵷</string><key>name</key><string>BODY_PARAMETER</string></dict>
<dict><key>begin</key><string>􏵴</string><key>end</key><string>􏵵</string><key>name</key><string>SELF_DATA_MEMBER</string></dict>
<dict><key>begin</key><string>􏵈</string><key>end</key><string>􏵉</string><key>name</key><string>LOCAL_DATA_MEMBER</string></dict>
<dict><key>begin</key><string>􏵆</string><key>end</key><string>􏵇</string><key>name</key><string>SUB_MEMBER</string></dict>
<dict><key>begin</key><string>􏵲</string><key>end</key><string>􏵳</string><key>name</key><string>SELF_FUNCTION_CALL</string></dict>
<dict><key>begin</key><string>􏵄</string><key>end</key><string>􏵅</string><key>name</key><string>FOREIGN_FUNCTION_CALL</string></dict>
<dict><key>begin</key><string>􏵢</string><key>end</key><string>􏵣</string><key>name</key><string>RETURN</string></dict>
</array></dict>
<dict><key>begin</key><string>􏷀</string><key>end</key><string>􏶿</string><key>name</key><string>FUNCTION_ARGUMENT_COMMENT</string><key>patterns</key><array>
<dict><key>match</key><string>􏵱</string><key>name</key><string>TRUE_MACRO</string></dict>
<dict><key>match</key><string>􏵰</string><key>name</key><string>FALSE_MACRO</string></dict>
</array></dict>
<dict><key>begin</key><string>􏶺</string><key>end</key><string>􏶹</string><key>name</key><string>FUNCTION_RESULT_COMMENT</string><key>patterns</key><array>
<dict><key>match</key><string>􏵱</string><key>name</key><string>TRUE_MACRO</string></dict>
<dict><key>match</key><string>􏵰</string><key>name</key><string>FALSE_MACRO</string></dict>
</array></dict>
<dict><key>begin</key><string>􏶠</string><key>end</key><string>􏶡</string><key>name</key><string>FUNCTION_DETAILED_DESCRIPTION</string><key>patterns</key><array>
<dict><key>match</key><string>􏵱</string><key>name</key><string>TRUE_MACRO</string></dict>
<dict><key>match</key><string>􏵰</string><key>name</key><string>FALSE_MACRO</string></dict>
</array></dict>
<dict><key>begin</key><string>􏷐</string><key>end</key><string>􏷏</string><key>name</key><string>FUNCTION_BRIEF_DESCRIPTION</string><key>patterns</key><array>
<dict><key>match</key><string>􏵱</string><key>name</key><string>TRUE_MACRO</string></dict>
<dict><key>match</key><string>􏵰</string><key>name</key><string>FALSE_MACRO</string></dict>
</array></dict>
<dict><key>begin</key><string>􏶞</string><key>end</key><string>􏶟</string><key>name</key><string>META_DATA_CODE_TYPE</string></dict>
<dict><key>begin</key><string>􏷲</string><key>end</key><string>􏷱</string><key>name</key><string>META_DATA_BRIEF_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏷰</string><key>end</key><string>􏷯</string><key>name</key><string>META_DATA_DETAILED_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏷮</string><key>end</key><string>􏷭</string><key>name</key><string>META_DATA_GROUP_NAME</string></dict>
<dict><key>begin</key><string>􏷬</string><key>end</key><string>􏷫</string><key>name</key><string>META_DATA_AUTHOR</string></dict>
<dict><key>begin</key><string>􏷪</string><key>end</key><string>􏷩</string><key>name</key><string>META_DATA_BUG</string></dict>
<dict><key>begin</key><string>􏷨</string><key>end</key><string>􏷧</string><key>name</key><string>META_DATA_WARNING</string></dict>
<dict><key>begin</key><string>􏷖</string><key>end</key><string>􏷕</string><key>name</key><string>META_DATA_DEPRECIATION</string></dict>
<dict><key>begin</key><string>􏴃</string><key>end</key><string>􏴄</string><key>name</key><string>META_SUBGROUP_NAME</string></dict>
<dict><key>begin</key><string>􏴁</string><key>end</key><string>􏴂</string><key>name</key><string>META_SUBGROUP_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏵔</string><key>end</key><string>􏵕</string><key>name</key><string>META_SPECIFICATION_FILE_PATH</string></dict>
<dict><key>begin</key><string>􏵒</string><key>end</key><string>􏵓</string><key>name</key><string>META_SPECIFICATION_FILE_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏴋</string><key>end</key><string>􏴌</string><key>name</key><string>META_FORSEEABLE_CHANGE</string></dict>
<dict><key>begin</key><string>􏴉</string><key>end</key><string>􏴊</string><key>name</key><string>META_FORSEEABLE_CHANGE_REASON</string></dict>
<dict><key>begin</key><string>􏴇</string><key>end</key><string>􏴈</string><key>name</key><string>META_FORSEEABLE_REASON_PERCENTAGE</string></dict>
<dict><key>begin</key><string>􏷤</string><key>end</key><string>􏷣</string><key>name</key><string>IMPORT_INTERFACE_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏷦</string><key>end</key><string>􏷥</string><key>name</key><string>IMPORT_INTERFACE_NAME</string></dict>
<dict><key>begin</key><string>􏷢</string><key>end</key><string>􏷡</string><key>name</key><string>IMPORT_INTERFACE_COMMENT</string></dict>
<dict><key>begin</key><string>􏴓</string><key>end</key><string>􏴔</string><key>name</key><string>IMPORT_INTERFACE_RELATIONSHIP</string></dict>
<dict><key>begin</key><string>􏴑</string><key>end</key><string>􏴒</string><key>name</key><string>IMPORT_INTERFACE_RELATED</string></dict>
<dict><key>begin</key><string>􏶔</string><key>end</key><string>􏶕</string><key>name</key><string>IMPORT_IMPLEMENTATION_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏶒</string><key>end</key><string>􏶓</string><key>name</key><string>IMPORT_IMPLEMENTATION_NAME</string></dict>
<dict><key>begin</key><string>􏶖</string><key>end</key><string>􏶗</string><key>name</key><string>IMPORT_IMPLEMENTATION_COMMENT</string></dict>
<dict><key>begin</key><string>􏴏</string><key>end</key><string>􏴐</string><key>name</key><string>IMPORT_IMPLEMENTATION_RELATIONSHIP</string></dict>
<dict><key>begin</key><string>􏴍</string><key>end</key><string>􏴎</string><key>name</key><string>IMPORT_IMPLEMENTATION_RELATED</string></dict>
<dict><key>begin</key><string>􏷠</string><key>end</key><string>􏷟</string><key>name</key><string>NAMESPACE_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏷞</string><key>end</key><string>􏷝</string><key>name</key><string>NAMESPACE_NAME</string></dict>
<dict><key>begin</key><string>􏷜</string><key>end</key><string>􏷛</string><key>name</key><string>INHERITANCE_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏷚</string><key>end</key><string>􏷙</string><key>name</key><string>INHERITANCE_TYPE</string></dict>
<dict><key>begin</key><string>􏳹</string><key>end</key><string>􏳺</string><key>name</key><string>FORWARD_DECLARE_ARGUMENT</string></dict>
<dict><key>begin</key><string>􏷘</string><key>end</key><string>􏷗</string><key>name</key><string>FUNCTION_CLASS_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏷔</string><key>end</key><string>􏷓</string><key>name</key><string>FUNCTION_OPERATION_CATEGORY</string></dict>
<dict><key>begin</key><string>􏴅</string><key>end</key><string>􏴆</string><key>name</key><string>FUNCTION_SUBGROUP_NAME</string></dict>
<dict><key>begin</key><string>􏷐</string><key>end</key><string>􏷏</string><key>name</key><string>FUNCTION_BRIEF_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏶠</string><key>end</key><string>􏶡</string><key>name</key><string>FUNCTION_DETAILED_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏷒</string><key>end</key><string>􏷑</string><key>name</key><string>FUNCTION_NAME</string></dict>
<dict><key>begin</key><string>􏴫</string><key>end</key><string>􏴬</string><key>name</key><string>FUNCTION_UNIQUE_MANGLE_NAME</string></dict>
<dict><key>begin</key><string>􏴳</string><key>end</key><string>􏴴</string><key>name</key><string>FUNCTION_ALTERNATIVE_EXPRESSION_NAME</string></dict>
<dict><key>begin</key><string>􏵪</string><key>end</key><string>􏵫</string><key>name</key><string>FUNCTION_PRECONDITION</string></dict>
<dict><key>begin</key><string>􏵨</string><key>end</key><string>􏵩</string><key>name</key><string>FUNCTION_PRECONDITION_COMMENT</string></dict>
<dict><key>begin</key><string>􏵦</string><key>end</key><string>􏵧</string><key>name</key><string>FUNCTION_POSTCONDITION</string></dict>
<dict><key>begin</key><string>􏵤</string><key>end</key><string>􏵥</string><key>name</key><string>FUNCTION_POSTCONDITION_COMMENT</string></dict>
<dict><key>begin</key><string>􏷎</string><key>end</key><string>􏷍</string><key>name</key><string>FUNCTION_TEMPLATE_ARGUMENT_TYPE</string></dict>
<dict><key>begin</key><string>􏷌</string><key>end</key><string>􏷋</string><key>name</key><string>FUNCTION_TEMPLATE_ARGUMENT_IDENTIFIER</string></dict>
<dict><key>begin</key><string>􏷊</string><key>end</key><string>􏷉</string><key>name</key><string>FUNCTION_TEMPLATE_ARGUMENT_DEFAULT</string></dict>
<dict><key>begin</key><string>􏷈</string><key>end</key><string>􏷇</string><key>name</key><string>FUNCTION_TEMPLATE_ARGUMENT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶜</string><key>end</key><string>􏶝</string><key>name</key><string>FUNCTION_ARGUMENT_TYPE_QUALIFIERS</string></dict>
<dict><key>begin</key><string>􏷆</string><key>end</key><string>􏷅</string><key>name</key><string>FUNCTION_ARGUMENT_TYPE</string></dict>
<dict><key>begin</key><string>􏷄</string><key>end</key><string>􏷃</string><key>name</key><string>FUNCTION_ARGUMENT_IDENTIFIER</string></dict>
<dict><key>begin</key><string>􏵘</string><key>end</key><string>􏵙</string><key>name</key><string>FUNCTION_ARGUMENT_UNITS</string></dict>
<dict><key>begin</key><string>􏷂</string><key>end</key><string>􏷁</string><key>name</key><string>FUNCTION_ARGUMENT_DEFAULT</string></dict>
<dict><key>begin</key><string>􏷀</string><key>end</key><string>􏶿</string><key>name</key><string>FUNCTION_ARGUMENT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶚</string><key>end</key><string>􏶛</string><key>name</key><string>FUNCTION_RESULT_TYPE_QUALIFIERS</string></dict>
<dict><key>begin</key><string>􏶾</string><key>end</key><string>􏶽</string><key>name</key><string>FUNCTION_RESULT_TYPE</string></dict>
<dict><key>begin</key><string>􏶼</string><key>end</key><string>􏶻</string><key>name</key><string>FUNCTION_RESULT_IDENTIFIER</string></dict>
<dict><key>begin</key><string>􏵜</string><key>end</key><string>􏵝</string><key>name</key><string>FUNCTION_RESULT_UNITS</string></dict>
<dict><key>begin</key><string>􏶺</string><key>end</key><string>􏶹</string><key>name</key><string>FUNCTION_RESULT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶸</string><key>end</key><string>􏶷</string><key>name</key><string>EXCEPT_EXPRESSION</string></dict>
<dict><key>begin</key><string>􏶶</string><key>end</key><string>􏶵</string><key>name</key><string>EXCEPT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶴</string><key>end</key><string>􏶳</string><key>name</key><string>FUNCTION_BODY</string></dict>
<dict><key>begin</key><string>􏴱</string><key>end</key><string>􏴲</string><key>name</key><string>FUNCTION_TEST_CASE_NAME</string></dict>
<dict><key>begin</key><string>􏴯</string><key>end</key><string>􏴰</string><key>name</key><string>FUNCTION_TEST_CASE_TAG</string></dict>
<dict><key>begin</key><string>􏴭</string><key>end</key><string>􏴮</string><key>name</key><string>FUNCTION_TEST_CASE_BODY</string></dict>
<dict><key>begin</key><string>􏴥</string><key>end</key><string>􏴦</string><key>name</key><string>TYPEDEF_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏴣</string><key>end</key><string>􏴤</string><key>name</key><string>TYPEDEF_BRIEF_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏴡</string><key>end</key><string>􏴢</string><key>name</key><string>TYPEDEF_DETAILED_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏴟</string><key>end</key><string>􏴠</string><key>name</key><string>TYPEDEF_NAME</string></dict>
<dict><key>begin</key><string>􏴝</string><key>end</key><string>􏴞</string><key>name</key><string>TYPEDEF_RETURN</string></dict>
<dict><key>begin</key><string>􏴛</string><key>end</key><string>􏴜</string><key>name</key><string>TYPEDEF_RETURN_COMMENT</string></dict>
<dict><key>begin</key><string>􏴙</string><key>end</key><string>􏴚</string><key>name</key><string>TYPEDEF_ARGUMENT</string></dict>
<dict><key>begin</key><string>􏴗</string><key>end</key><string>􏴘</string><key>name</key><string>TYPEDEF_ARGUMENT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶨</string><key>end</key><string>􏶧</string><key>name</key><string>DATA_MEMBER_BRIEF</string></dict>
<dict><key>begin</key><string>􏶦</string><key>end</key><string>􏶥</string><key>name</key><string>DATA_MEMBER_DETAILED</string></dict>
<dict><key>begin</key><string>􏶘</string><key>end</key><string>􏶙</string><key>name</key><string>DATA_MEMBER_CLASS_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏶰</string><key>end</key><string>􏶯</string><key>name</key><string>DATA_MEMBER_TYPE_QUALIFIERS</string></dict>
<dict><key>begin</key><string>􏶮</string><key>end</key><string>􏶭</string><key>name</key><string>DATA_MEMBER_TYPE</string></dict>
<dict><key>begin</key><string>􏶬</string><key>end</key><string>􏶫</string><key>name</key><string>DATA_MEMBER_IDENTIFIER</string></dict>
<dict><key>begin</key><string>􏵚</string><key>end</key><string>􏵛</string><key>name</key><string>DATA_MEMBER_UNITS</string></dict>
<dict><key>begin</key><string>􏶪</string><key>end</key><string>􏶩</string><key>name</key><string>DATA_MEMBER_DEFAULT_VALUE</string></dict>
<dict><key>begin</key><string>􏴷</string><key>end</key><string>􏴸</string><key>name</key><string>DATA_MEMBER_PARTIAL_PACK_AMOUNT</string></dict>
<dict><key>begin</key><string>􏵁</string><key>end</key><string>􏵂</string><key>name</key><string>DATA_MEMBER_PAIR_KEY</string></dict>
<dict><key>begin</key><string>􏴿</string><key>end</key><string>􏵀</string><key>name</key><string>DATA_MEMBER_PAIR_VALUE</string></dict>
<dict><key>begin</key><string>􏴽</string><key>end</key><string>􏴾</string><key>name</key><string>DATA_MEMBER_CONSTRAINT_OPERATION</string></dict>
<dict><key>begin</key><string>􏴵</string><key>end</key><string>􏴶</string><key>name</key><string>DATA_MEMBER_CONSTRAINT_VALUE</string></dict>
<dict><key>begin</key><string>􏴻</string><key>end</key><string>􏴼</string><key>name</key><string>DATA_MEMBER_DEFINED_VALUE</string></dict>
<dict><key>begin</key><string>􏴹</string><key>end</key><string>􏴺</string><key>name</key><string>DATA_MEMBER_DEFINED_VALUE_MEANING</string></dict>
<dict><key>begin</key><string>􏳷</string><key>end</key><string>􏳸</string><key>name</key><string>DATA_MEMBER_TRANSITION_BEFORE_OPERATION</string></dict>
<dict><key>begin</key><string>􏳵</string><key>end</key><string>􏳶</string><key>name</key><string>DATA_MEMBER_TRANSITION_BEFORE_VALUE</string></dict>
<dict><key>begin</key><string>􏳳</string><key>end</key><string>􏳴</string><key>name</key><string>DATA_MEMBER_TRANSITION_AFTER_OPERATION</string></dict>
<dict><key>begin</key><string>􏳱</string><key>end</key><string>􏳲</string><key>name</key><string>DATA_MEMBER_TRANSITION_AFTER_VALUE</string></dict>
<dict><key>begin</key><string>􏳯</string><key>end</key><string>􏳰</string><key>name</key><string>DATA_MEMBER_TRANSITION_MEANING</string></dict>
<dict><key>begin</key><string>􏶊</string><key>end</key><string>􏶉</string><key>name</key><string>ENUM_BRIEF</string></dict>
<dict><key>begin</key><string>􏶈</string><key>end</key><string>􏶇</string><key>name</key><string>ENUM_DETAIL</string></dict>
<dict><key>begin</key><string>􏶀</string><key>end</key><string>􏶋</string><key>name</key><string>ENUM_NAME</string></dict>
<dict><key>begin</key><string>􏵮</string><key>end</key><string>􏵯</string><key>name</key><string>ENUM_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏵬</string><key>end</key><string>􏵭</string><key>name</key><string>ENUM_BASE_TYPE</string></dict>
<dict><key>begin</key><string>􏳿</string><key>end</key><string>􏴀</string><key>name</key><string>ENUM_SUBGROUP_NAME</string></dict>
<dict><key>begin</key><string>􏳽</string><key>end</key><string>􏳾</string><key>name</key><string>ENUM_SUBGROUP_DESCRIPTION</string></dict>
<dict><key>begin</key><string>􏶆</string><key>end</key><string>􏶅</string><key>name</key><string>ENUM_ARG_NAME</string></dict>
<dict><key>begin</key><string>􏶄</string><key>end</key><string>􏶃</string><key>name</key><string>ENUM_ARG_VALUE</string></dict>
<dict><key>begin</key><string>􏶂</string><key>end</key><string>􏶁</string><key>name</key><string>ENUM_ARG_COMMENT</string></dict>
<dict><key>begin</key><string>􏳻</string><key>end</key><string>􏳼</string><key>name</key><string>ENUM_ARG_GROUP_AFFILIATION</string></dict>
<dict><key>begin</key><string>􏵐</string><key>end</key><string>􏵑</string><key>name</key><string>MACRO_SPECIFIERS</string></dict>
<dict><key>begin</key><string>􏵾</string><key>end</key><string>􏵿</string><key>name</key><string>MACRO_NAME</string></dict>
<dict><key>begin</key><string>􏵖</string><key>end</key><string>􏵗</string><key>name</key><string>MACRO_UNITS</string></dict>
<dict><key>begin</key><string>􏴩</string><key>end</key><string>􏴪</string><key>name</key><string>MACRO_ARGUMENT_IDENTIFIER</string></dict>
<dict><key>begin</key><string>􏴧</string><key>end</key><string>􏴨</string><key>name</key><string>MACRO_ARGUMENT_COMMENT</string></dict>
<dict><key>begin</key><string>􏵺</string><key>end</key><string>􏵻</string><key>name</key><string>MACRO_BRIEF</string></dict>
<dict><key>begin</key><string>􏵸</string><key>end</key><string>􏵹</string><key>name</key><string>MACRO_DETAIL</string></dict>
<dict><key>begin</key><string>􏵼</string><key>end</key><string>􏵽</string><key>name</key><string>MACRO_VALUE</string></dict>
<dict><key>begin</key><string>􏵠</string><key>end</key><string>􏵡</string><key>name</key><string>FILE_WIDE_INVARIANT</string></dict>
<dict><key>begin</key><string>􏵞</string><key>end</key><string>􏵟</string><key>name</key><string>FILE_WIDE_INVARIANT_COMMENT</string></dict>
<dict><key>begin</key><string>􏶤</string><key>end</key><string>􏶣</string><key>name</key><string>RUN_SHELL_COMMAND</string></dict>
<dict><key>begin</key><string>􏵎</string><key>end</key><string>􏵏</string><key>name</key><string>TEST_CASE_NAME</string></dict>
<dict><key>begin</key><string>􏵌</string><key>end</key><string>􏵍</string><key>name</key><string>TEST_CASE_TAG</string></dict>
<dict><key>begin</key><string>􏵊</string><key>end</key><string>􏵋</string><key>name</key><string>TEST_CASE_BODY</string></dict>
</array><key>scopeName</key><string>text.UniLang</string><key>uuid</key>
<string>112dad9d-558e-4ab2-a4cc-c5f1ffa80ee6</string></dict></plist>
