package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "method_utility_function_getter", deps = [
"//code/transcompilers/unilang/structure/model/sections/data_member:data_member_item",
"//code/transcompilers/unilang/options/sections/data_member:data_member_options",
"//code/transcompilers/unilang/structure/print:doxygen_block_printer",
"//code/transcompilers/unilang/structure/print:function_declaration_location",
"//code/transcompilers/unilang/options/manipulation/methods/via_other_methods:method_utility_function_options",
"//code/utilities/converters:lib",
"//code/utilities/types/strings/transformers/casing:lib",
])