package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "direct_methods_called_by_methods_getter",
#     deps = [
#         "//code/utilities/code/query:argument_direction_decider",
#         "//code/utilities/comments/doxygen/settings:doxygen_parameter_direction",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/variant:lib",
#     ],
# )

# hcp(
#     name = "direct_method_call_and_count",
#     deps = [
#     ],
# )
