load("//bazel/cookbook/cpp:main.bzl", "cpp_main")
package(
    default_visibility = ["//visibility:public"],
)

cpp_main(
    name = "timer",
    deps = ["@stopwatch//:stopwatch"],
)

cpp_main(
    name = "function_time",
    deps = ["@stopwatch//:stopwatch"],
)

cpp_main(
    name = "function_sample",
    deps = ["@stopwatch//:stopwatch"],
)