#!/usr/bin/env zsh

docker_rmi_dependants
docker_rm_dangling
docker images
echo "---"
docker container ls --size

#!/bin/bash
# Delete all containers
docker rm $(docker ps -a -q)
# Delete all images
docker rmi $(docker images -q)