package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "component_input",
#     deps = [
#     ],
# )

# hcp(
#     name = "component_output",
#     deps = [
#     ],
# )

# hcp(
#     name = "input_struct_getter",
#     deps = [
#         "component_input",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "object_name_resolver",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "component_struct_printer",
#     deps = [
#         "component_input",
#         "component_output",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "api_printer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "in_out_design_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#     ],
# )
