package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "stock_getter",deps=[
"//code/utilities/streams/filestreams:lib",
"//code/utilities/filesystem/paths:lib",
"//code/utilities/program/call:lib",
"//code/utilities/web:lib",
])