package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "cpp_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/linguistics/computer:source_language",
#     ],
# )

# hcp(
#     name = "cpp_options_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/meta/settings/organizations:organization",
#         "//code/utilities/personal/life:company_getter",
#         "//code/utilities/program/common_actions/exits:lib",
#     ],
# )
