package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp_hdrs_derive(
#     name = "json_print_method_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp_hdrs_derive(
#     name = "to_json_method_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp_hdrs_derive(
#     name = "serialize_json_method_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/other:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )
