package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

# hcp(
#     name = "fully_read_file",
#     deps = [
#         "//code/utilities/streams/filestreams/read_all:lib",
#     ],
# )

# hcp(
#     name = "actionable_code_graphs_creator",
#     deps = [
#     ],
# )

# hcp(
#     name = "exception_handler",
#     deps = [
#
#         "//code/utilities/language_basic/std_hackery:lib",
#     ],
# )

# hcp(
#     name = "dependency_path_validator",
#     deps = [
#         "//code/utilities/filesystem/paths:lib",
#     ],
# )

# hcp(
#     name = "user_frontend",
#     deps = [
#     ],
# )

# hcp(
#     name = "code_graphs_creator",
#     deps = [
#         "//code/utilities/types/strings/transformers/stripping:lib",
#     ],
# )

# hcp(
#     name = "program_input_enricher",
#     deps = [
#         "//code/utilities/filesystem/files/getting:lib",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/output/diagnostic:diagnostic_printer",
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "transcompiler",
#     deps = [
#     ],
# )

# hcp(
#     name = "after_artifact_actions",
#     deps = [
#
#         "//code/utilities/filesystem/files/getting:lib",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/output/diagnostic:diagnostic_printer",
#         "//code/utilities/program/call:lib",
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/stripping:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp(
#     name = "file_to_structure_converter",
#     deps = [
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "language_guesser",
#     deps = [
#         "//code/utilities/formats/artifact:artifact_type",
#     ],
# )

# hcp(
#     name = "workspace_adjuster",
#     deps = [
#         "//code/utilities/filesystem/files/getting:lib",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )
