package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "contract_postcondition",
#     deps = [
#     ],
# )

# hcp(
#     name = "contract_precondition",
#     deps = [
#     ],
# )

# hcp(
#     name = "method_contracts_section",
#     deps = [
#         "contract_postcondition",
#         "contract_precondition",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )
