#!/usr/bin/env bash

#regular color messages
function black_message() { echo -e "\033[1;30m$@\033[0m";}
function red_message() { echo -e "\033[1;31m$@\033[0m";}
function green_message() { echo -e "\033[1;32m$@\033[0m";}
function yellow_message() { echo -e "\033[1;33m$@\033[0m";}
function blue_message() { echo -e "\033[1;34m$@\033[0m";}
function purple_message() { echo -e "\033[1;35m$@\033[0m";}
function cyan_message() { echo -e "\033[1;36m$@\033[0m";}
function white_message() { echo -e "\033[1;37m$@\033[0m";}

# generic success/error messages
function error_message() { echo -e "\033[1;31m$@\033[m" 1>&2;}
function success_message() { echo -e "\033[1;32m$@\033[0m";}
