#!/usr/bin/env bash


#stack based directory changing.  
#Used to step into directories, and make conversion based on relative path,
#steping out after can be done automatically.
function Silently_Go_Back_To_The_Previous_Pwd(){
  popd > /dev/null 2>&1;
}
function Step_In_Call_Function_Step_Out(){
  pushd $1 > /dev/null 2>&1;          #step in
  $2;                                   #call function
  Silently_Go_Back_To_The_Previous_Pwd; #step out
}
