package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "printf_print_statement_creator",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "printf_transition_statement_creator",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts/data_member:data_member_options",
#         "//code/utilities/types/converters:lib",
#     ],
# )
