package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     "slidy_settings",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/markdown/settings:markdown_settings",
#         "//code/utilities/linguistics/computer/frontends/parts:portion_options",
#     ],
# )

# hcp(
#     "slidy_creation_settings",
#     deps = [
#     ],
# )
