package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "hcp-compiler",
    srcs = ["main.cpp"],
    deps = ["//code/transcompilers/hcp-compiler/bootstrap/program_options:lib",
            "//code/transcompilers/hcp-compiler/bootstrap/core:core",
            "//code/utilities/locale:lib"]
)