package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "update_with_bools_printer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "update_with_enums_printer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "update_printer",
#     deps = [
#         "update_with_bools_printer",
#         "update_with_enums_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )
