#!/bin/zsh
unilang --input_files shard_queue.unilang --exporter UBER --languages JAVA --style NORMAL --build-only;
cp RedisQueue.java ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/queues/; 
java -jar ~/Desktop/buildfarm/java_formatter.jar -i ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/queues/RedisQueue.java