#!/bin/zsh
source ~/.zshrc

function transcompile {
    unilang --input_files $1.unilang --exporter UBER --languages JAVA --style NORMAL --build-only;
    cp $2.java $3; 
    java -jar ~/Desktop/buildfarm/java_formatter.jar -i "${3}""${2}".java
}

#redis queues
transcompile redis_queue RedisQueue ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/queues/
transcompile redis_provision_queue RedisProvisionQueue ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/queues/
transcompile redis_provision_queues RedisProvisionQueues ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/queues/

#shard backplane
transcompile jedis_cluster_factory JedisClusterFactory ~/Desktop/buildfarm/src/main/java/build/buildfarm/instance/shard/