#!/bin/zsh
source ~/.zshrc

function transcompile {
    unilang --input_files $1.unilang --exporter UBER --languages JAVA --style NORMAL --build-only;
    transfer $2 $3;
}

function transcompile_test {
    unilang --input_files $1.unilang --exporter UBER --languages JAVA_TEST --style NORMAL --build-only;
    transfer $2 $3;
}

function transfer {
    cp $1.java $2;
    rm $1.java;
}

function format {
    cd ~/Desktop/bazel-buildfarm;
    .bazelci/format.sh
    cd -;
}

#resource limits
#cd resource_limits;
#transcompile cpu_limits CpuLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
#transcompile gpu_limits GpuLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
#transcompile mem_limits MemLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
#transcompile disk_limits DiskLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
#transcompile network_limits NetworkLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
#transcompile time_limits TimeLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
# transcompile resource_limits ResourceLimits ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
# transcompile resource_decider ResourceDecider ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/resources
# transcompile_test resource_decider ResourceDeciderTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/worker/resources
# cd ..;

#cd execution;
#transcompile execution_debugger ExecutionDebugger ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/


#transcompile grpc_endpoint GrpcEndpoint ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/grpc
#transcompile grpc_endpoint_handler GrpcEndpointHandler ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/grpc

#redis data structures
transcompile redis_map RedisMap ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile_test redis_map RedisMapMockTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/

#transcompile cas_worker_map CasWorkerMap ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/instance/shard/


#redis queues
#transcompile redis_queue RedisQueue ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis
#transcompile_test redis_queue RedisQueueTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis
#transfer RedisQueueMockTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/instance/shard/queues/

#balanced queues
#transcompile balanced_redis_queue BalancedRedisQueue ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis
#transcompile_test balanced_redis_queue BalancedRedisQueueTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/instance/shard/queues/
#transfer BalancedRedisQueueMockTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/instance/shard/queues/

#transcompile      provisioned_redis_queue ProvisionedRedisQueue   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile_test provisioned_redis_queue ProvisionedRedisQueueTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/

#transcompile operation_queue OperationQueue ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/instance/shard/

#transcompile      filtered_provisions FilteredProvisions   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile      eligibility_result EligibilityResult   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/

#transcompile      time Time   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/
#transcompile      size Size   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/

transcompile      scan_count ScanCount   ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/


#transcompile cas_indexer CasIndexer ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/instance/shard/

#transcompile redis_slot_to_hash RedisSlotToHash ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile_test redis_slot_to_hash RedisSlotToHashTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/

#transcompile redis_hashtags RedisHashtags ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile_test redis_hashtags RedisHashtagsTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/

#transcompile redis_node_hashes RedisNodeHashes ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/redis/
#transcompile_test redis_node_hashes RedisNodeHashesTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/
#transfer RedisNodeHashesMockTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/common/redis/

#cd indexing;
#transcompile cas_index_settings CasIndexSettings ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/
#transcompile cas_index_results CasIndexResults ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/
#transcompile worker_indexer WorkerIndexer ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/

#cd finding;
#transcompile enriched_operation EnrichedOperation ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/operations/
#transcompile enriched_operation_builder EnrichedOperationBuilder ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/operations/
#transcompile find_operations_settings FindOperationsSettings ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/operations/
#transcompile find_operations_results FindOperationsResults ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/operations/
#transcompile operations_finder OperationsFinder ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/operations/

# cd match;
# transcompile dequeue_match_settings DequeueMatchSettings ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/
# transcompile dequeue_match_evaluator DequeueMatchEvaluator ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/worker/
# transcompile_test dequeue_match_evaluator DequeueMatchEvaluatorTest ~/Desktop/bazel-buildfarm/src/test/java/build/buildfarm/worker/



# transcompile string_visitor StringVisitor ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/common/


#shard backplane
# transcompile jedis_cluster_factory JedisClusterFactory ~/Desktop/bazel-buildfarm/src/main/java/build/buildfarm/instance/shard/


format;

#missing java automations:
# - correct package name
# - forwarding constructors
# - better test mocking