#!/usr/bin/env zsh
REDSHIFT_LEVEL=3000
killall fluxgui >/dev/null 2>&1;
killall fluxgui >/dev/null 2>&1;
nohup redshift-gtk -r -O$REDSHIFT_LEVEL >/dev/null 2>&1 &
nohup redshift-gtk -r -O$REDSHIFT_LEVEL >/dev/null 2>&1 &
