package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "special_type_json_specifier_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/types/converters:lib",
#     ],
# )
