package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "root_settings",
#     deps = [
#     ],
# )

# hcp(
#     name = "root_settings_getter",
#     deps = [
#     ],
# )

# hcp(
#     name = "initial_diagnostics",
#     deps = [
#         "//code/utilities/output/diagnostic:diagnostic_settings",
#     ],
# )
