package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "type_to_hungarian_notation_converter",
#     deps = [
#         "//code/utilities/linguistics/computer/hungarian/settings:identifier_notation_settings",
#     ],
# )

# hcp(
#     name = "data_member_to_hungarian_notation_converter",
#     deps = [
#         "//code/utilities/linguistics/computer/hungarian/settings:identifier_notation_settings",
#         "//code/utilities/types/converters:lib",
#     ],
# )
