#!/usr/bin/env bash


current_branch_name=`git rev-parse --abbrev-ref HEAD`;
new_branch_name=`echo "$1" | tr -s ' ' | tr ' ' '-'`;
git branch -m $current_branch_name $new_branch_name;  # Rename branch locally    
git push origin :$current_branch_name;                # Delete the old branch    
git push --set-upstream origin $new_branch_name;      # Push the new branch, set local branch to track the new remote