#!/usr/bin/env bash
#./split-pr original-branch "new PR title" files...

branch="$1";
message="$2";
new_branch=$branch-split-$RANDOM
files="${@:3}";

git checkout -b $new_branch
git checkout $branch $files
git push
