#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

# Get the current branch name.
curr_branch=$(git rev-parse --abbrev-ref HEAD)

# Loop until we hit the master branch.
while [ $curr_branch != "master" ]; do
# Run arc update on the current diff.
echo "Updating $curr_branch ..."
arc-update

# Checkout the upstream branch.
git checkout --quiet @{u} 

# If there are no more upstream branches we are also done.
if [ $? != 0 ]
then
    echo "Exiting early, no more upstream branches."
    break
fi

# Get the current branch name.
curr_branch=$(git rev-parse --abbrev-ref HEAD)
done