#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#fuzzy search for branch checkout (quickly change branches by using a matching substring)

git checkout `git branch -a |  #list all the branches
grep $1 |                      #filter out only ones that match the substring
head -n 1 |                    #get just the first result
sed 's/remotes\/origin\///g' | #trims off the "remote/orign" portion
sed 's/  //g'`;                #trim off whitespace

#-if a local branch doesn't exist, 
#and there is only the remote branch, 
#this will trim off the "remote/orign" portion
#and allow git to create the local branch for you
