package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")
load("//bazel/cookbook/enum_cpp:enum_cpp.bzl", "enum_cpp")

hcp(name = "f310_gamepads_state_getter", deps = [
    "//code/utilities/peripheral/keyboard/F310_gamepad/data:f310_gamepads"
])