package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "good_api_creator",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "deep_copy_creator",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )
