package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

# hcp(
#     name = "actionable_code_graphs",
#     deps = [
#     ],
# )

# hcp(
#     name = "actionable_code_graph",
#     deps = [
#         "//code/utilities/data_structures/graph/unique_vertex_graph:lib",
#     ],
# )

# hcp(
#     name = "code_graphs_to_actionable_graphs",
#     deps = [
#     ],
# )
