class
❪string❫
❪vector❫
❪"code/bazel_refresh/conversion_test/bazel_conversion_tests"❫
⚯
❪"code/utilities/filesystem/paths/lib"❫
❪"code/utilities/filesystem/files/creating/lib"❫
❪"code/utilities/types/strings/transformers/appending/lib"❫
❪"code/utilities/types/vectors/converters/lib"❫
❪"code/utilities/filesystem/files/deleting/lib"❫
❪"code/utilities/types/strings/transformers/casing/lib"❫
❪"code/bazel_refresh/conversion_test/test_getter"❫
❪"code/bazel_refresh/readme_creator"❫
❪"code/transcompilers/unilang/file_extension_getter/file_extension_getter"❫
⚞⚟

◀public: static▶ void ☀Refresh()❰
❱