
cc_binary(
    name = "annotation_tool_summary",
    srcs = ["annotation_tool_summary.cc"],
    deps = [
    "//code/utilities/mouse:mouse_controller",
    ],
    linkopts = ["-lXcursor", "-lxdo"],
)