#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

amount="$@";

#if no amount is given, we'll assume 0
if [ -z "$amount" ]; then
  amount=0;
fi

amount=`expr $amount + 1`
pattern="-c"$amount"-";
cut $pattern;
