package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/enum_cpp:enum_cpp.bzl", "enum_cpp")

hcp(
    name = "setup_display_settings",
    deps = [
        "@x11",
    ],
)

hcp(
    name = "x11_main_state_creator",
    deps = [
        ":setup_display_settings",
        "//code/utilities/graphics/x11/data:main_x11_state",
        "//code/utilities/graphics/x11/data:x11_bg_fg_colors",
        "//code/utilities/graphics/x11/data:x11_window_geometry",
        "@x11",
    ],
)
