package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="gcal_room", deps = [
])
hcp(name="gcal_rooms", deps = [
    "//code/utilities/gcal/data:gcal_room"
])