package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "dzslides_settings_getter",
    deps = [
        "//code/tools/transcompilers/old_unilang/options/language-specific/dzslides:dzslides_settings",
    ],
)

hcp(
    name = "dzslides_exporter",
    deps = [
        "//code/tools/transcompilers/old_unilang/options/language-specific/dzslides:dzslides_settings",
        "//code/tools/transcompilers/old_unilang/options/manipulation:case_adjustment_settings",
        "//code/tools/transcompilers/old_unilang/structure/adjust:casing_adjuster",
        "//code/tools/transcompilers/old_unilang/structure/adjust:structure_adjuster",
        "//code/tools/transcompilers/old_unilang/structure/model:inlined_structures",
        "//code/tools/transcompilers/old_unilang/structure/model:structure",
        "//code/tools/transcompilers/old_unilang/structure/print:struct_derivers",
        "//code/utilities/contributor",
        "//code/utilities/filesystem/files/creating:lib",
        "//code/utilities/filesystem/paths:lib",
        "//code/utilities/linguistics/computer/file_extension:file_extension_getter",
        "//code/utilities/linguistics/grammar:grammar_adjuster",
        "//code/utilities/program/call:lib",
        "//code/utilities/program/common_actions/exits:lib",
        "//code/utilities/types/char:lib",
        "//code/utilities/types/converters:lib",
        "//code/utilities/types/strings/observers/other:lib",
        "//code/utilities/types/strings/transformers/appending:lib",
        "//code/utilities/types/strings/transformers/casing:case_modifier",
        "//code/utilities/types/vectors/observers:lib",
        "//code/utilities/types/vectors/operators:lib",
    ],
)
