package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "temp_file",
    srcs = ["temp_file.cpp"],
    hdrs = ["temp_file.hpp"],
    deps = [
    "//code/utilities/filesystem/files/creating:lib",
    "//code/utilities/filesystem/files/deleting:lib"
],
)
