package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "regular_statement", deps = [
"//code/transcompilers/unilang/parser:token_value"
])

hcp(name = "return_statement", deps = [
"//code/transcompilers/unilang/parser:token_value"
])