package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "bazel_rule_exporter",
#     deps = [
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )
