package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "protobuf_exporter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/protobuf/settings:protocol_buffer_export_settings",
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl:header_printer",
#         "//code/utilities/types/char:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/other:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )

# hcp(
#     name = "protobuf_options_getter",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/protobuf/settings:protocol_buffer_export_settings",
#         "//code/utilities/linguistics/computer/frontends/parts/meta/settings/organizations:organization",
#         "//code/utilities/personal/life:company_getter",
#         "//code/utilities/program/common_actions/exits:lib",
#     ],
# )
