package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")
load("//bazel/cookbook/enum_cpp:enum_cpp.bzl", "enum_cpp")

hcp(name = "default_initialize_getter", deps = [
    "//code/tools/transcompilers/unilang/structure/model/sections/data_member:data_member_item",
    "//code/utilities/linguistics/computer:source_language",
    "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
    "//code/tools/transcompilers/unilang/structure/print/derivers:type_name_deriver",
    "//code/utilities/types/strings/observers/converting:lib",
    "//code/utilities/types/converters:lib",
])