package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "bazel_rule_exporter",
#     deps = [
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/bazel/bazel_printer:build_info_extractor",
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/bazel/bazel_printer:load_getter",
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/bazel/bazel_printer:package_getter",
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/bazel/bazel_printer:top_comment_getter",
#         "//code/tools/transcompilers/old_unilang/compiler-frontends/bazel/bazel_printer/rule_getter",
#         "//code/tools/transcompilers/old_unilang/dependency_graph_creator:code_graph",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler:file_transferer",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_settings",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_transfer_action",
#         "//code/tools/transcompilers/old_unilang/f2si_frontend_compiler/pulse:pulse_transferer",
#         "//code/tools/transcompilers/old_unilang/options/bazel:build_rule_settings",
#         "//code/tools/transcompilers/old_unilang/options/bazel:language_to_build_object",
#         "//code/tools/transcompilers/old_unilang/user-frontend/artifact_actions:artifact_guesser",
#         "//code/utilities/contributor",
#         "//code/utilities/filesystem/paths:lib",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/vectors/transformers:lib",
#     ],
# )
