package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "body_param_in_method_printer",
#     deps = [
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "data_member_in_method_printer",
#     deps = [
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )

# hcp(
#     name = "foreign_method_call_in_method_printer",
#     deps = [
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "method_call_in_method_printer",
#     deps = [
#         "//code/utilities/colors:lib",
#         "//code/utilities/program/common_actions/exits:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/casing:lib",
#     ],
# )
