package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="crosshair_mouse", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="tree_expand_symbol", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])