package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="crosshair_mouse", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="tree_expand_symbol", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="tree_collapse_symbol", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="tree_button", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap_button",
    "//code/utilities/data_structures/graphics/bitmap/premade:tree_collapse_symbol",
    "//code/utilities/data_structures/graphics/bitmap/premade:tree_expand_symbol",
])

hcp(name="vertical_line", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="horizontal_line", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])

hcp(name="l_line", deps = [
    "//code/utilities/data_structures/graphics/bitmap/multi_color_bitmap:multi_color_bitmap",
])