package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "shared_printer",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/observers/comparing:lib",
#         "//code/utilities/types/strings/transformers/appending:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#         "//code/utilities/types/strings/transformers/casing:lib",
#         "//code/utilities/types/strings/transformers/removing:lib",
#     ],
# )

# hcp(
#     name = "stream_creator",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/linguistics/computer/frontends/parts/filesystem:general_filesystem_naming",
#     ],
# )

# cpp_object(name = "function_declaration_location")

# hcp(
#     name = "doxygen_block_printer",
#     deps = [
#         "//code/utilities/comments/doxygen/maker:doxygen_block_maker",
#         "//code/utilities/comments/doxygen/maker:doxygen_data",
#         "//code/utilities/comments/doxygen/maker:doxygen_data_getter",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/other:lib",
#     ],
# )

# hcp(
#     name = "data_member_printer",
#     deps = [
#         "//code/utilities/linguistics/computer:source_language",
#         "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
#         "//code/utilities/linguistics/computer/literals/getter:literal_suffix_getter",
#         "//code/utilities/linguistics/computer/literals/getter/data:literal_suffix_settings",
#         "//code/utilities/linguistics/computer/types/default_initialize:default_initialize_getter",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "method_body_token_printer",
#     deps = [
#         "//code/utilities/comments/code:comment_creator",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#         "//code/utilities/types/variant:lib",
#     ],
# )

# hcp(
#     name = "namespace_printer",
#     deps = [
#         "//code/utilities/comments/doxygen/maker:doxygen_data_getter",
#         "//code/utilities/linguistics/computer/frontends/parts/namespace:namespace_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "return_type_str_getter",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "method_block_ender",
#     deps = [
#         "//code/utilities/comments/code:comment_creator",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "implicit_contract_adder",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "methods_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "method_signature_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/strings/transformers/casing:case_modifier",
#     ],
# )

# hcp(
#     name = "struct_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts:portion_options",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "hidl_data_member_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/parts:portion_options",
#         "//code/utilities/linguistics/computer/literals/adjuster:literal_adjuster",
#         "//code/utilities/linguistics/computer/types/generic:unilang_type_to_language_type_converter",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "object_printer",
#     deps = [
#         "object_file_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "object_file_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "actual_structure_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#     ],
# )

# hcp(
#     name = "global_printer",
#     deps = [
#         "//code/utilities/linguistics/computer/export_file_settings",
#         "//code/utilities/linguistics/computer/frontends/parts/extern_c:extern_wrap_printer",
#         "//code/utilities/linguistics/computer/frontends/parts/header/impl:header_printer",
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp(
#     name = "file_printer",
#     deps = [
#         "//code/utilities/streams/filestreams:lib",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/general:lib",
#         "//code/utilities/types/vectors/operators:lib",
#     ],
# )

# hcp(
#     name = "struct_derivers",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )

# hcp(
#     name = "type_specialize_getter",
#     deps = [
#         "//code/utilities/types/converters:lib",
#     ],
# )
