package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

cpp_object(name="attribute_technique")
hcp(name="attribute_style",
deps=[
"//code/transcompilers/unilang/options/sections/method/attributes/specific/parts:attribute_technique"
])
hcp(name="attribute_usage_note")