package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "lib",
    srcs = ["lib.cpp"],
    hdrs = ["lib.hpp"],
    deps = [
        "//code/utilities/types/strings/observers/converting:lib",
        "//code/utilities/program/common_actions/exits:lib",
        "//code/utilities/shell/process_spawn:process_spawner",
    ]
)
