package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(
    name = "red_cursor",
    deps = [
        "//code/utilities/colors:color_defaults",
        "//code/utilities/data_structures/graphics/objects/cursor:label_cursor",
    ],
)

hcp(
    name = "blue_cursor",
    deps = [
        "//code/utilities/colors:color_defaults",
        "//code/utilities/data_structures/graphics/objects/cursor:label_cursor",
    ],
)
