package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="red_cursor", deps = [
    "//code/utilities/data_structures/graphics/objects/cursor:label_cursor",
    "//code/utilities/colors:color_defaults",
])

hcp(name="blue_cursor", deps = [
    "//code/utilities/data_structures/graphics/objects/cursor:label_cursor",
    "//code/utilities/colors:color_defaults",
])