package(default_visibility = ["//visibility:public"])
load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/hcp:hcp_and_hcp_pos.bzl", "hcp_and_hcp_pos")

cpp_object(name = "stb_image",
    deps = [
    "@stb"
    ],
)