package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "method_subgroup_tag_settings",
    deps = [
        "//code/utilities/comments/code/settings:comment_settings",
    ],
)

hcp(
    name = "method_sorting_settings",
    deps = [
        "//code/utilities/linguistics/computer/frontends/parts/method/sorting/method_sort_algorithms",
    ],
)
