package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/image:png_to_xpm.bzl", "png_to_xpm")
load("//bazel/cookbook/image:xpm_to_ppm.bzl", "xpm_to_ppm")
load("//bazel/cookbook/image:ppm_to_mask.bzl", "ppm_to_mask")

png_to_xpm("mario1")
xpm_to_ppm("mario1")
ppm_to_mask("mario1")