package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

hcp(
    name = "flag_util",
    deps = [
        "//code/utilities/program/inputs/flags/data:flags",
        "//code/utilities/types/vectors/observers:lib",
    ],
)
