# These targets are designed to help experiment with buildfarm's CAS hardlinking implementation.

package(
    default_visibility = ["//visibility:public"],
)

sh_test(
    name = "main",
    srcs = ["main.sh"],
)

sh_test(
    name = "main2",
    srcs = ["main.sh"],
)