#!/usr/bin/env bash
#see what the team is up to
#doesn't really work on certain workflows where there is a queue bot
git log --graph -20 --branches --remotes --tags  --format=format:'%Cgreen%h %Creset %<(75,trunc)%s (%cN, %cr) %Cred%d' --date-order
