package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")
load("//bazel/rules/cpp:distributable_main.bzl", "distributable_cpp_main")

hcp(
    name = "bes_metrics",
    deps = [
    ],
)

hcp(
    name = "workspace_metrics",
    deps = [
    ],
)

hcp(
    name = "filesystem_metrics",
    deps = [
    ],
)

hcp(
    name = "aquery_metrics",
    deps = [
    ],
)
