package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "secret_getter",deps=[
"//code/utilities/streams/filestreams/read_all:lib",
"//code/utilities/filesystem/paths:lib",
])