package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "sdl_audio",
    srcs = ["sdl_audio.c"],
    hdrs = ["sdl_audio.h"],
    deps = [
        "@sdl2//:SDL2",
    ],
)
