package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "struct_manipulation_settings",
#     deps = [
#     ],
# )

# hcp(
#     name = "token_case_settings",
#     deps = [
#         "//code/utilities/types/strings/transformers/casing:case_format_style",
#     ],
# )

# hcp(
#     name = "case_adjustment_settings",
#     deps = [
#         "token_case_settings",
#     ],
# )

# hcp(
#     name = "comment_adjustment_settings",
#     deps = [
#         "//code/utilities/linguistics/grammar/settings:comment_grammar_settings",
#     ],
# )
