#deps needed:

#other things to add
#gmp
#json (ttps://github.com/nlohmann/json)
#pretty_printers
#curl
#pstreams
#add-range-v3 library (Eric Neibler)
#add klmr-cpp11-range

#need to make hermetic
#sudo apt-get install libsdl2-dev
#sudo apt-get install libsdl1.2-dev
#sudo apt install libjpeg9-dev libwebp-dev libtiff5-dev libsdl2-image-dev libsdl2-image-2.0-0
new_http_archive(
      name = "imgui",
      urls = ['https://github.com/ocornut/imgui/archive/v1.62.tar.gz'],
      build_file = "bazel/deps/imgui.BUILD",
      strip_prefix = 'imgui-1.62',
)

#need to make hermetic
#sudo apt-get install xdotool
#sudo apt-get install libxdo-dev
#sudo apt-get install libxtst-dev
new_git_repository(
    name = "xdo",
    build_file = "bazel/deps/xdo/xdo.BUILD",
    commit = "08c8e2d6cad60a69ce415499e34865157a1b66fd",
    remote = "https://github.com/jordansissel/xdotool.git",
)

load("//bazel/deps:third_party.bzl", "third_party_repositories")
third_party_repositories()
