load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

################################################
# Pulling in and building clang
load("//bazel/toolchains:toolchains.bzl", "toolchains")
toolchains()

load("@com_grail_bazel_toolchain//toolchain:rules.bzl", "llvm_toolchain")

llvm_toolchain(
    name = "llvm_toolchain",
    llvm_version = "8.0.0",
)
################################################
# Ideally we don't want to create these, but sometimes things are too hard to build from source
new_local_repository(
    name = "SDL2",
    build_file = "//bazel/deps/build_files:sdl2-local.BUILD",
    path = "/usr",
)

#new_local_repository(
#    name = "SFML",
#    build_file = "//bazel/deps/build_files:sfml-local.BUILD",
#    path = "/usr",
#)

new_local_repository(
    name = "opengl",
    build_file = "//bazel/deps/build_files:opengl-local.BUILD",
    path = "/usr",
)
new_local_repository(
	name = "python_context",
        build_file = "//bazel/deps/build_files:python_context.BUILD",
        path = "/usr/include/python3.6m",
)
################################################
load("@io_bazel_rules_m4//:m4.bzl", "m4_register_toolchains")
m4_register_toolchains()

load("//bazel/deps:third_party_libraries.bzl", "third_party_libraries")
third_party_libraries()

load("@build_stack_rules_proto//cpp:deps.bzl", "cpp_proto_compile")
cpp_proto_compile()
################################################
# Import "rules_foreign_cc".
# These are all an attempt to run cmake builds inside bazel

# Group the sources of the library so that CMake rule have access to it
all_content = """filegroup(name = "all", srcs = glob(["**"]), visibility = ["//visibility:public"])"""

git_repository(
    name = "rules_foreign_cc",
    remote = "https://github.com/bazelbuild/rules_foreign_cc.git",
    commit = "5511d9e1fe7219075ea8191298808c654974c6ac",
)

load("@rules_foreign_cc//:workspace_definitions.bzl", "rules_foreign_cc_dependencies")

# Workspace initialization function; includes repositories needed by rules_foreign_cc,
# and creates some utilities for the host operating system
rules_foreign_cc_dependencies()
################################################
