package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# cpp_object(name = "code_partition_method")

# cpp_object(name = "constraint_export_style")

# hcp(name = "test_wrapper_options")

# hcp(
#     name = "general_options",
#     deps = [
#         "//code/utilities/comments/code/settings:comment_settings",
#         "//code/utilities/linguistics/computer/frontends/parts/filesystem:general_filesystem_naming",
#     ],
# )

# hcp(
#     name = "foreign_language_export_settings",
#     deps = [
#         "//code/utilities/linguistics/computer/frontends/protobuf/settings:protocol_buffer_export_settings",
#         "//code/utilities/linguistics/computer/frontends/markdown/settings:markdown_settings",
#     ],
# )

# hcp(
#     name = "export_settings",
#     deps = [
#         "foreign_language_export_settings",
#     ],
# )

# hcp(name = "remote_build_settings")

# hcp(name = "remote_program_settings")

# hcp(name = "workspace_settings")

# hcp(name = "test_case_attribute_settings")
