#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

#for now, we'll just say that "tag branches" are the ones that have a "UHMEP-" in it
if print-branch-name | grep -q "UHMEP-"; then 
    exit $true;
fi

exit $false;
