package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:hcp.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "mouse_controller",deps=[
"//code/utilities/xdo:lib",
"//code/utilities/data_structures/point:point",
"//code/utilities/time/sleeping:lib",
"//code/utilities/random:lib",
])