package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "macro_item",
#     deps = [
#     ],
# )

# hcp(
#     name = "macro_section",
#     deps = [
#         "macro_item",
#     ],
# )
