#!/usr/bin/env bash
. $HOME/.bin/scripts/project/src/utility_functions/bootstrap; #
#-----------------------------------------#

# completely detached from terminal 
nohup $@ </dev/null >/dev/null 2>&1 &
