load("//bazel/cookbook/cpp:main.bzl", "cpp_main")

package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "@Xau",
        "@xcb",
    ],
)

cc_binary(
    name = "main2",
    srcs = ["main2.cpp"],
    deps = [
        "@Xau",
        "@xcb",
    ],
)
