package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "special_json_specifier_settings",
#     deps = [
#         "special_json_type",
#         "special_type_json_builder",
#     ],
# )

# hcp(
#     name = "special_json_type",
#     deps = [
#     ],
# )

# hcp(
#     name = "special_type_json_builder",
#     deps = [
#         "special_json_type",
#     ],
# )
