package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:hcp.bzl", "hcp")
load("//bazel/cookbook:cpp_object.bzl", "cpp_object")

hcp(name = "method_names_section", deps = [
"//code/transcompilers/unilang/parser:token_value",
"alternative_expression_name"
])
hcp(name = "alternative_expression_name", deps = [
"//code/transcompilers/unilang/parser:token_value",
])