package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook:core.bzl", "hcp","cpp_object")

hcp(name = "method_names_section", deps = [
"//code/transcompilers/unilang/parser:token_value",
"alternative_expression_name"
])
hcp(name = "alternative_expression_name", deps = [
"//code/transcompilers/unilang/parser:token_value",
])