package(
    default_visibility = ["//visibility:public"],
)

cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        "//code/tools/games/math_game/assets:assets_loader",
        "//code/utilities/games/patchwork/data:piece_getter",
    ],
)
