#!/usr/bin/env bash
watch -n .1 'echo "NODES:"; \
kubectl get nodes; \
echo "\nENDPOINTS:"; \
kubectl get endpoints; \
echo "\nDEPLOYMENTS:"; \
kubectl get deployments; \
echo "\nSERVICES:"; \
kubectl get service --all-namespaces; \
echo "\nPODS:"; \
kubectl get pods -o wide;'
