package(default_visibility = ["//visibility:public"])

load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(
    name = "image_settings",
    deps = [
        "//code/utilities/data_structures/dimensions:two_d_dimensions",
    ],
)