# cc_binary(
#     name = "mouse_manual_presentation",
#     srcs = ["main.cc"],
#     deps = [
#     "//code/utilities/peripheral/mouse:mouse_controller",
#     ],
#     linkopts = ["-lXcursor", "-lxdo"],
# )
