package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "structure_static_analyzer",
#     deps = [
#         ":error_message",
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/sets:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )

# hcp(
#     name = "error_message",
#     deps = [
#     ],
# )

# hcp(
#     name = "error_message_printer",
#     deps = [
#     ],
# )

# hcp(
#     name = "error_message_getter",
#     deps = [
#         "//code/utilities/types/converters:lib",
#         "//code/utilities/types/sets:lib",
#         "//code/utilities/types/strings/observers/splitting:lib",
#         "//code/utilities/types/strings/transformers/trimming:lib",
#     ],
# )
