package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "predefined_characters", deps = [
"//code/utilities/fonts/bdf/settings:bdf_settings",
"//code/utilities/fonts/bdf/glyph:glyphs",
])