package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:hcp.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name="basic_html_template_getter",deps = [
    "//code/utilities/types/vectors/creators:lib",
    "//code/utilities/types/vectors/observers:lib",
    "//code/utilities/filesystem/files/creating:lib",
    "//code/utilities/types/strings/transformers/appending:lib",
])