package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")

hcp(name = "all_method_attribute_settings",deps = [
"//code/tools/transcompilers/unilang/options/sections/method/attributes/specific/argument:argument_attribute_settings",
"//code/tools/transcompilers/unilang/options/sections/method/attributes/specific/method:method_attribute_settings"
])