package(default_visibility = ["//visibility:public"])

load("@com_github_grpc_grpc//bazel:cc_grpc_library.bzl", "cc_grpc_library")
load("@com_github_grpc_grpc//bazel:grpc_build_system.bzl", "grpc_proto_library")

grpc_proto_library(
    name = "hellostreamingworld",
    srcs = ["hellostreamingworld.proto"],
)

proto_library(
    name = "helloworld_proto",
    srcs = ["helloworld.proto"],
)

cc_proto_library(
    name = "helloworld_cc_proto",
    deps = [":helloworld_proto"],
)

cc_grpc_library(
    name = "helloworld_cc_grpc",
    srcs = [":helloworld_proto"],
    grpc_only = True,
    deps = [":helloworld_cc_proto"],
)

cc_binary(
    name = "greeter_client",
    srcs = ["cpp/helloworld/greeter_client.cc"],
    defines = ["BAZEL_BUILD"],
    deps = [
        ":helloworld_cc_grpc",
        # "//:grpc++",
        "@com_github_grpc_grpc//:grpc++",
    ],
)

# cc_binary(
#     name = "greeter_async_client",
#     srcs = ["cpp/helloworld/greeter_async_client.cc"],
#     defines = ["BAZEL_BUILD"],
#     deps = [
#         ":helloworld_cc_grpc",
#         "//:grpc++",
#     ],
# )

# cc_binary(
#     name = "greeter_async_client2",
#     srcs = ["cpp/helloworld/greeter_async_client2.cc"],
#     defines = ["BAZEL_BUILD"],
#     deps = [
#         ":helloworld_cc_grpc",
#         "//:grpc++",
#     ],
# )

# cc_binary(
#     name = "greeter_server",
#     srcs = ["cpp/helloworld/greeter_server.cc"],
#     defines = ["BAZEL_BUILD"],
#     deps = [
#         ":helloworld_cc_grpc",
#         "//:grpc++",
#         "//:grpc++_reflection",
#     ],
# )

# cc_binary(
#     name = "greeter_async_server",
#     srcs = ["cpp/helloworld/greeter_async_server.cc"],
#     defines = ["BAZEL_BUILD"],
#     deps = [
#         ":helloworld_cc_grpc",
#         "//:grpc++",
#     ],
# )
