package(default_visibility = ["//visibility:public"])
load("//bazel/cookbook/hcp:main.bzl", "hcp")
load("//bazel/cookbook/cpp:object.bzl", "cpp_object")


hcp(name = "bdf_settings_to_format", deps = [
   "//code/utilities/bdf/settings:bdf_settings"
])