load("//bazel/cookbook/cpp:main.bzl", "cpp_main")
package(
    default_visibility = ["//visibility:public"],
)

cpp_main(name = "main")

#probably need a newer compiler
#cpp_main(name = "for_each", copts=["--std=c++1z"])