package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "literature_section",
#     deps = [
#     ],
# )

# hcp(
#     name = "paragraph",
#     deps = [
#     ],
# )

# hcp(
#     name = "sentence",
#     deps = [
#     ],
# )

# hcp(
#     name = "sentence_image",
#     deps = [
#     ],
# )

# hcp(
#     name = "sentence_image_size",
#     deps = [
#     ],
# )

# hcp(
#     name = "sentence_tag",
#     deps = [
#     ],
# )

# hcp(
#     name = "outline_point",
#     deps = [
#     ],
# )

# hcp(
#     name = "thought_connection",
#     deps = [
#     ],
# )

# hcp(
#     name = "code_line",
#     deps = [
#     ],
# )

# hcp(
#     name = "reference_citation",
#     deps = [
#     ],
# )
