package(default_visibility = ["//visibility:public"])

load("//bazel/rules/hcp:hcp.bzl", "hcp")
load("//bazel/rules/hcp:hcp_hdrs_derive.bzl", "hcp_hdrs_derive")
load("//bazel/rules/cpp:object.bzl", "cpp_object")

# hcp(
#     name = "enums_adjuster",
#     deps = [
#     ],
# )

# hcp(
#     name = "enum_standard_incrementer",
#     deps = [
#
#     ],
# )

# hcp(
#     name = "enum_value_inserter",
#     deps = [
#     ],
# )
